### ISSUE TITLE
Support for Hunspell dictionaries

### ISSUE THREAD

**Issue by AlekSi** [Jason-Rev/vscode-spell-checker#1]
It would be nice to be able to use Hunspell (including non-English) dictionaries instead of built-in ones.

**Comment by Jason-Rev** [comment]
I am working on a way to import hunspell dictionaries.

**Comment by Jason-Rev** [comment]
Do you have a particular hunspell dictionary in mind?  If so, can you point me to it.  It is generally two files like: en_US.aff and en_US.dic.

**Comment by AlekSi** [comment]
I use my personal dictionary combined from several sources. You can check with one from [OpenOffice](http://extensions.openoffice.org/en/search?f[0]=field_project_tags%3A157) or [Mozilla](https://addons.mozilla.org/firefox/language-tools/).

**Comment by Jason-Rev** [comment]
Update.  This is still in progress.  I have a hunspell reader, but I am working on a way to reduce the number of generated words.  For example the spanish dictionary generates around 700k words.  The actual number of root words is much smaller, 59k.

**Comment by Jason3S** [comment]
Indirect support for Hunspell dictionaries has been added.

It is now possible to add your own custom dictionary. [how-to-add-your-own-dictionaries](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md#how-to-add-your-own-dictionaries)

I have also added a repository for optional dictionaries: [cSpell-WordLists](https://github.com/Jason3S/cSpell-WordLists)

**Comment by Jason3S** [comment]
Closing for now.
