### ISSUE TITLE
"Add <word> to dictionary" update global settings.json

### ISSUE THREAD

**Issue by bensallen** [Jason-Rev/vscode-spell-checker#10]
Could you add an option to allow the user to specify the action of "Add \<word\> to dictionary" to save the new word in the user's settings.json - cSpell.userWords list instead of in the workspace's .vscode/cSpell.json?

Thanks,

Ben

**Comment by Jason-Rev** [comment]
Thank you for the suggestion.

**Comment by fyelles** [comment]
I have the same issue. I wish I could save to a global list of words...
At the moment, I have to sync again multiple workspace which is somewhat of a pain

**Comment by Jason-Rev** [comment]
Thank you for letting me know.  I am working on the internals of dealing with multiple word lists.  Once that is done, I'll address this issue.

**Comment by Jason3S** [comment]
With the new version of vscode, being able to do this will be easier.

**Comment by Jason3S** [comment]
With release 0.11.1, by default words are now added to the User (Global) Dictionary.
