### ISSUE TITLE
Spelling not being checked (on .adoc file)

### ISSUE THREAD

**Issue by mgroves** [Jason-Rev/vscode-spell-checker#101]
I'm not sure when this stopped working, but spell checking does not seem to be working when I'm editing .adoc files anymore.

I thought maybe the File Type had been dislodged during an update or something (I'm on 1.13.1 of VSCode). But now I don't see a Spell Checker status in the status bar anymore. Is there some other way to make sure that this extension is included in the spell check?

I've attached a screenshot, hopefully that will help. Is there any other information that might be helpful?

![clipboard01](https://user-images.githubusercontent.com/103484/27499335-47865966-5831-11e7-8f57-a995aad7c42e.jpg)

**Comment by Jason3S** [comment]
Thank you.  I'll see if I can reproduce the issue.

**Comment by Jason3S** [comment]
Looks like the extension may have crashed or wasn't able to load. This can happen if vscode `reloads`.

Try exiting vscode and see if there are any vscode processing still running. You might need to kill them.

**Comment by Jason3S** [comment]
Please let me know if you are still seeing this issue.

**Comment by mgroves** [comment]
Hmm, I didn't see any VSCode processes running, but it must have been something like that. A reboot and spell checking is working correctly again. Thanks!

**Comment by Jason3S** [comment]
Thank you.  I'll close this.
