### ISSUE TITLE
Offline spellchecking?

### ISSUE THREAD

**Issue by alallier** [Jason-Rev/vscode-spell-checker#104]
Does this extension spell checking offline? If so that would be a great item to add to the FAQ.

**Comment by alallier** [comment]
Upon closer examination of the README I found the line I was looking for

> The spellchecker uses a local word dictionary. It does not send anything outside your machine.

Going to close

**Comment by Jason-Rev** [comment]
Still a good idea to add to the FAQ. Thank you for bringing this up.

**Comment by alallier** [comment]
You're welcome
