### ISSUE TITLE
Improving dictionaries generation

### ISSUE THREAD

**Issue by AlekSi** [Jason-Rev/vscode-spell-checker#11]
Currently `go.txt` [has](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/dictionaries/go.txt#L1133) `Float64frombits`. It is not generated by [go-words](https://github.com/AlekSi/go-words/blob/master/main.go) since it [strips non-alpha characters](https://github.com/AlekSi/go-words/blob/master/main.go#L48). How should those words be generated? Should it be two words `Float` and `frombits` or single "word" `Float64frombits`?

**Comment by AlekSi** [comment]
One more question: should this list include words from popular third-party Go packages? I propose to make a separate file for them like `go_packages.txt`.

**Comment by Jason-Rev** [comment]
Hello Alek,

Good questions.

I prefer complete names like: `Float64frombits`.  The spell checker will break them up when loading it into the dictionary.  At some point, I hope to make it context aware, and when that happens, having the complete name is more useful.

Adding the common third-party Go packages to a separate file is a good idea.

**Comment by AlekSi** [comment]
#14
