### ISSUE TITLE
cSpell ignore words in cSpell.json when you configured "cSpell.userWords" in user settings

### ISSUE THREAD

**Issue by hangxingliu** [Jason-Rev/vscode-spell-checker#114]
cSpell version: `1.3.0`

Easy reproduce way:

1. create double spelling mistake in a file.
2. fix one mistake by clicking popup menu item ` add "xxx" to dictionary`
3. fix other one mistake by clicking popup menu item ` add "yyy" to project dictionary`
4. then reload your VS Code.(you can ignore this step if you fixed #112 )
5. the spell checking result you got will be one word is correct and other one is wrong although you add these two words into dictionary in step 2, 3.

---
I browsed `git difftool -d 1.3.0 1.2.1` in your repository.  And I found this bug maybe from here:

``` typescript
// File: server/src/server.ts

// version 1.2.1
const defaultSettings = getDefaultSettings();
// version 1.3.0
const defaultSettings = CSpell.mergeSettings(getDefaultSettings(), CSpell.getGlobalSettings());
```

**Comment by Jason3S** [comment]
Thank you. I'll check it out.

**Comment by Jason3S** [comment]
I was not able to reproduce this behavior.

Please check to make sure your `workspace` `settings.json` files doe not contain `"cspell.userWords"`. If it exists, it will cancel out anything you have in user settings.

**Comment by Jason3S** [comment]
Please upgrade to 1.3.1, It fixes #112.

**Comment by hangxingliu** [comment]
I checked `settings.json` in workspace `.vscode` folder. There has not any cSpell configurations.

**Comment by Jason3S** [comment]
I cannot reproduce the issue.

Which word is not being found? The project level word or user level word?

Guess:
- If there is a syntax error in the cspell.json file, it will not load.

**Comment by hangxingliu** [comment]
LOL, I cannot reproduce it again. And I don't know the reason.

Maybe I upgrade to 1.3.1 or other reasons
