### ISSUE TITLE
highlight first item in suggestions by default

### ISSUE THREAD

**Issue by WickyNilliams** [Jason-Rev/vscode-spell-checker#115]
To save a few keystrokes, would it be possible to have the first item in the quickfix suggestions list highlighted? Since the top item in the list will be the correct value most of the time, it's reasonable to have it selected by default, saving the user from pressing the down arrow

**Comment by Jason3S** [comment]
That would be nice. I am not sure if that is possible, since VS Code controls that interaction. But there might be some option to send to VS Code to get it to select the first item.

**Comment by WickyNilliams** [comment]
Ah that's a shame. Hopefully there's a way to make this happen

**Comment by Jason3S** [comment]
Closing for now since this is not possible.

**Comment by WickyNilliams** [comment]
vscode now does this itself 😄
