### ISSUE TITLE
Support for PowerShell

### ISSUE THREAD

**Issue by Glober777** [Jason-Rev/vscode-spell-checker#12]
It would be really cool if this extension would also support checking PowerShell files. Are there any plans to add that capability?

**Comment by Jason-Rev** [comment]
Hello Globber,

I am working on an easier way to enable/disable the spellchecker for different languages.  But that is not done yet.  In the meantime, it is possible to enable PowerShell by changing your user settings file.  F1 -> Open User Settings

Generally in the left pane are the default settings and in the right pane are your user settings.

Search in the left pane for `cSpell.enabledLanguageIds`.  Copy the entire structure to your user settings in the right pane.  I am not sure of the language id for powershell, but my guess is that it is just 'powershell'.  

```yaml
    // Specify file types to spell check.
    "cSpell.enabledLanguageIds": [
        "csharp",
        "go",
        "javascript",
        "javascriptreact",
        "html",             // <-- example adding html
        "markdown",
        "php",
        "plaintext",
        "powershell",       // <-- add powershell id into your user settings.
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ],
```

After you save, you may need to relaunch for the setting to take hold.

Please let me know how it goes.

If you have a list of keywords that you think need to be added to fully support powershell, please send them to me and I will add  them.

Cheers,
Jason

**Comment by Jason-Rev** [comment]
UI support for this will be added with #13
