### ISSUE TITLE
only comment need a spell checking

### ISSUE THREAD

**Issue by zzzgit** [Jason-Rev/vscode-spell-checker#122]
hello, is there a way to config this plugin to perform only in comment, but not in code?

**Comment by Jason3S** [comment]
Please see if the answers here [FAQ is it possible to check only comments](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/FAQ.md#is-it-possible-to-only-spell-check-comments), work for you.

**Comment by Jason3S** [comment]
I'm going to close this. If you need any more info on how to get it to work, please let me know.
