### ISSUE TITLE
How to trigger suggestions is neither listed in description nor on the document.

### ISSUE THREAD

**Issue by C0deZLee** [Jason-Rev/vscode-spell-checker#126]
I suggest to add this very important information in the package description, to prevent new users (like me) search around for hours and still have no clue how to use it.

**Comment by Jason3S** [comment]
Thank you! I hadn't realized it was missing.

**Comment by Jason3S** [comment]
A fix will go out with the next release.

**Comment by C0deZLee** [comment]
Thank you :) 👍

**Comment by Jason3S** [comment]
This is what I have added to the [README](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md)

> To see the list of suggestions:
> - After positioning the cursor in the word, any of the following should dsiplay the list:
>   - Click on the 💡 (lightbulb) in the left had margin.
>   - Mac: `⌘`+`.` or `cmd`+`.`
>   - PC: `ctrl`+`.`
>
