### ISSUE TITLE
cSpell is activated before reading settings.

### ISSUE THREAD

**Issue by faustinoaq** [Jason-Rev/vscode-spell-checker#127]
Hi @Jason-Rev 

vscode: 1.15
os: Manjaro Linux KDE Gellivara

I set  `"cSpell.enabled": false` on `settings.json` but it keep analyzing files even when is disabled.

It only happens when I open a workspace with opened documents previously. If I open a empty workspace it won't happen. Seems that `cSpell` has a small delay reading `settings.json` so opened files are analized before.

Also I can see `cSpell` is always activated because this: [#L31](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/package.json#L31) (same issue as https://github.com/editorconfig/editorconfig-vscode/pull/159

![screenshot_20170815_094557](https://user-images.githubusercontent.com/3067335/29320981-99f215d2-819e-11e7-8b71-1ef48fb5f801.png)

BTW, thanks for this extension :smile:

**Comment by Jason3S** [comment]
Thank you.

Do you have an idea how long this has been happening?

**Comment by faustinoaq** [comment]
Well, It happen from day one I installed the extension. :sweat_smile: , I didn't realize because the errors disappear when you open another file or close the open one.

**Comment by faustinoaq** [comment]
I need to disable cSpell because I use it for specific workspaces only. By example: documents and papers in Markdown and Latex, or sometimes for Yaml and Json. Also I write in English and Spanish. So many configurations in differents workspaces. :sweat_smile:

**Comment by Jason3S** [comment]
Do you remember when you started using the extension? I am trying to determine when this behavior might have started.

I recently added a Spanish dictionary: [Spell Checker for Spanish](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-spanish). I would appreciate any feedback on how well it works for you.

**Comment by Jason3S** [comment]
As a work around, you can disable cspell in your user settings, then only enable it in each workspace.

**Comment by faustinoaq** [comment]
> As a work around, you can disable cspell in your user settings, then only enable it in each workspace.

Exactly what I'm doing

BTW, Spanish extension works like a charm, npm package `cspell-dict-es-es` is not needed now :+1:

**Comment by Jason3S** [comment]
Got it. I can see how this could happen. It is a race condition on startup.

**Comment by Jason3S** [comment]
I have pushed out a new version that should help with this issue.

But there are some more things going on. VS Code opens some files in the background. Only it isn't easy to tell that these files are in the background. The `settings.json` file is an example.  So is `package.json`.

**Comment by faustinoaq** [comment]
This bug is fixed with your latest version. Thanks you very much! :smile:
