### ISSUE TITLE
Having problems using in debug mode , can't put breakpoint

### ISSUE THREAD

**Issue by Jeyanthinath** [Jason-Rev/vscode-spell-checker#129]
Steps to reproduce:

1. Create a line with some spelling mistake 
2. Try debugging the file 
3. while debugging you can't able to put breakpoint 

Because the spelling mistake suggestion icon is occupying the breakpoint placeholder :(

**Comment by Jason3S** [comment]
Hello @Jeyanthinath,

Thank you. I can easily reproduce it. This is an issue with VS Code and how it displays `Diagnostic` results. Notice how it is also an issue if you have a linter or language error in your code, the 💡gets in the way.

See https://github.com/Microsoft/vscode/issues/25174

The work around is to move the cursor to another line.

**Comment by Jason3S** [comment]
Thank you for binging it up. I'm going to close this, unless you feel it is really just an issue with the spell checker.

**Comment by Jeyanthinath** [comment]
@Jason3S Thanks for the response :+1:
