### ISSUE TITLE
Make it easy to turn on / turn off spell checking for file types

### ISSUE THREAD

**Issue by Jason-Rev** [Jason-Rev/vscode-spell-checker#13]
# Summary

It would be useful to be able to enable / disable spell checking for a file or filetype right from the editor without needing to edit a settings.json file.

**Comment by Jason3S** [comment]
Documentation still needs to be written.  But it is now possible.

**Comment by AlekSi** [comment]
This issue is still in backlog there: https://github.com/Jason-Rev/vscode-spell-checker/projects/1

**Comment by Jason3S** [comment]
@AlekSi thank you, I haven't looked at the project board in ages.

To enable a doc type, `F1 Enable Spell Checking Document Language`.
I should change the name to `Enable Spell Checking Document Type`

**Comment by AlekSi** [comment]
Yeah, I know, it works for me, thanks. :)
