### ISSUE TITLE
High CPU code helper on large files

### ISSUE THREAD

**Issue by cklanac** [Jason-Rev/vscode-spell-checker#130]
Opening an issue about high cpu usage, as requested. 

I get a high CPU when opening large json files, which makes sense. The spell checker is trying to check nearly 25+k lines and 12 MB of data. The file is Mongo's [primer-dataset.json](https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json) from their tutorials

Tested Mac OS Sierra 10.12.6
- all extensions disabled, including code spell checker
   Open large file => CPU usage normal

- only code spell check extension enable
   Open and quickly close large file => High CPU for several minutes

- only code spell check extension enable
   Open and quickly close large file => High CPU for several minutes

- added the filename cSpell.ignorePaths array (see below)
   Open large file => CPU usage normal :-)

```
	"cSpell.ignorePaths": [
		"**/node_modules/**",
		"**/vscode-extension/**",
		"**/.git/**",
		".vscode",
		"typings",
		"primer-dataset.json"
	],
```

Honestly, I'm not sure what you can do to prevent the problem. Even the built-in syntax highlighter spikes for a couple seconds when I open a large file.

Maybe you can listen for the file close event and kill the process?

**Comment by Jason3S** [comment]
@cklanac thank you, this is excellent information!

One simple option is to set a configurable size limit on how much of a document is spell checked. A default of something like 500k should be reasonable for most cases.

**Comment by Jason3S** [comment]
I have added a new setting:
```javascript
// The limit in K-Bytes to be checked in a file.
"cSpell.checkLimit": 500,
```

**Comment by Jason3S** [comment]
Let me know if you see this issue again.
