### ISSUE TITLE
Do we have any option to spell check all folders or specified folders?

### ISSUE THREAD

**Issue by palashmon** [Jason-Rev/vscode-spell-checker#135]
Currently, spell check only becomes active on opening a file.
Is there any way or option to spell check all folders or specified folders on demand?

May be we can add an option like: 
`"cSpell.checkAllFolders": true` or `"cSpell.checkSelectedFolders": ["src", "routes"]`

Regards!

**Comment by Jason3S** [comment]
Please see the https://github.com/Jason-Rev/vscode-spell-checker/issues/111

**Comment by palashmon** [comment]
Yup, that is enough for me.

Thanks a ton!

**Comment by Jason3S** [comment]
I am glad it worked. Closing.
