### ISSUE TITLE
Clicking on lightbulb sometimes adds word to dictionary.

### ISSUE THREAD

**Issue by fryguybob** [Jason-Rev/vscode-spell-checker#138]
Sometimes when I click on the light bulb icon it will add the word to the dictionary.  This happens because the menu starts to show on the mouse down then if the mouse happens to be over a menu item on mouse up it triggers the selection of that item.  When a misspelled word is toward the bottom of the screen and there is not room for the menu to go down, it will go up from the cursor (I'm on Windows).  The add to dictionary entries are at the bottom of the menu so they appear right under the cursor for (at least some) clicks of the light bulb.  If the menu could always appear slightly away from the cursor this would at least require some movement of the mouse to click on the add to dictionary entry.

**Comment by Jason3S** [comment]
Sorry about not answering sooner.

Yes, that can be very annoying. The best thing is to file an issue with VSCode. I do not have control over the light-bulb.

**Comment by Jason3S** [comment]
@fryguybob did you manage to open an issue on VS Code?

**Comment by fryguybob** [comment]
Hi @Jason3S, the latest VSCode (Version 1.18.0) does not have this problem.  The menu does not open until the mouse up.

**Comment by Jason3S** [comment]
Great! Thank you.
