### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by anand-a6** [Jason-Rev/vscode-spell-checker#140]
It used to work like a charm but after the last update of vs code spell checker stopped working

**Comment by Jason3S** [comment]
Can you give me some more details so I can help?

Does it load? Did you get any errors?
Which OS are you using?
Do you see something like this on the info bar at the bottom of the window: 
![image](https://user-images.githubusercontent.com/3740137/30799876-94a63b34-a1de-11e7-9be1-dd0dc633726d.png)

If you right click in an editor window do you see the menu item: 
![image](https://user-images.githubusercontent.com/3740137/30799949-c42cf8a2-a1de-11e7-82eb-087dd103548c.png)

**Comment by jshap70** [comment]
I had to uninstall and reinstall the extension to get it to work. It was throwing "command not found" errors.

**Comment by Jason3S** [comment]
Good to know. thank you.

**Comment by anand-a6** [comment]
It works now, after i reinstalled it :).
