### ISSUE TITLE
allowCompoundWords only validates two words

### ISSUE THREAD

**Issue by dander401** [Jason-Rev/vscode-spell-checker#142]
"heat mapchart" is spelled correctly but "heatmapchart" is not. 

edit: words are hard

**Comment by Jason3S** [comment]
You are right. At the moment it only checks two words. One option is to allow it to be the maximum number of words.

**Comment by Jason3S** [comment]
There are two issues:
1. gibberish - three or more word combo make for some strange words.
2. performance - the current implementation is not cheap.

Possibilities:
- issue 1. is hard to address without adding a word pair frequency table (size issue).
- issue 2. is achievable.

**Comment by dander401** [comment]
What about just an option for how many words to allow. A note about performance in the comments would at least tell users to expect 2 words, allow them to change it at their own peril. I have only needed 3 words twice. And while 2 words makes sense, it seems like a bug without it being documented.

**Comment by Jason3S** [comment]
Yes, the comments need to be updated.

**Comment by Jason3S** [comment]
It will now spell check as many words as you have.
