### ISSUE TITLE
Spawns too many "find" processes

### ISSUE THREAD

**Issue by ypresto** [Jason-Rev/vscode-spell-checker#143]
I have no idea why but this extension spawns one `find` process per second in my environment.
![image](https://user-images.githubusercontent.com/400558/31118749-6e6eaae6-a869-11e7-8edc-d2594f4f1d6e.png)

Reproduced when disabling all other extensions, not reproduced when disabling this extension.

(Mac OS X 10.12.6, VSCode 1.16.1)

**Comment by madlou** [comment]
Not sure if its related, but since today, vscode uses 100% of my cpu, unless I disable this extension.

(Win7 64bit, 1.16.1)

**Comment by BillDenton** [comment]
Any update on this issue? This is making the extension unusable.

**Comment by Jason3S** [comment]
Thank you. I'm pushing out a fix now.

**Comment by madlou** [comment]
That’s great, thanks for the quick turnaround- really appreciate all the work you put in on the extension- it’s really useful.

**Comment by Jason3S** [comment]
I was using a VS Code method to find the settings files. apparently it is VERY inefficient. It launches all the `find` commands.

I have turned off the code that searches for the local config.

**Comment by ypresto** [comment]
Thanks!!

> I was using a VS Code method to find the settings files. apparently it is VERY inefficient. It launches all the find commands.

Could you tell me which method it is? It might be vscode-side performance issue.

**Comment by madlou** [comment]
>Could you tell me which method it is? It might be vscode-side performance issue.

Looking at his first commit for the fix, I assume the issue was with:

`vscode.workspace.findFiles(findConfig, '{**/node_modules,**/.git}');`

**Comment by Jason3S** [comment]
The original change went in to work around an issue with: `workspace.createFileSystemWatcher(configFileWatcherGlob);`
I was getting complaints about performance when someone opened vscode on a large project.

So, I switched to a polling method using `workspace.findFiles`. This proved to be even worse.

The final solution was to poll for the existence of explicit files and set watchers on them.
