### ISSUE TITLE
disable scrollbar annotations

### ISSUE THREAD

**Issue by krasi-georgiev** [Jason-Rev/vscode-spell-checker#144]
Can you please add an option to disable scroll bar marking for misspelled words or if not possible maybe add an option to choose colour so I can select the same colour as the scrollbar background.

I like to keep the scrollbar clean and show only git changes , compilation errors , search results etc.

**Comment by Jason3S** [comment]
I don't have control over the scrollbar. Please see #128 

One other option is to bind the spell checker enable / disable command to a key combination, then you can turn it on / off with just a key stroke.

**Comment by krasi-georgiev** [comment]
so based on #128 can't you set it to`DiagnosticSeverity.Hint | no color` ?

**Comment by Jason3S** [comment]
It is possible to enhance the spell checker allow the `DiagnosticServerity` to be set to `Hint`.  That would mean the squiggles and the scroll bar colors don't show up at all.

**Comment by krasi-georgiev** [comment]
Where do I set this option ? Could you give an example.

**Comment by Jason-Rev** [comment]
I didn't build it yet.

**Comment by Jason-Rev** [comment]
When I wrote "possible" to do.

**Comment by krasi-georgiev** [comment]
Ah , ok.
From what I understood this option would disable both - underlining and srollbar markings? 
I guess you can't leave the underlining and set only the scrollbar to hint so that it doesn't show ?

**Comment by Jason3S** [comment]
I have added the ability to change the diagnostic level to any of the following:
`Error`, `Warning`, `Information`, `Hint`.

If you go to the User or Workspace Settings, you can set the option like this:
```json
"cSpell.diagnosticLevel": "Hint"
```

Hint will hide it from the text and scroll bar. The issues will still show up in the "Problems" window.
