### ISSUE TITLE
Add word to Dictionary doesn't work

### ISSUE THREAD

**Issue by HaojinDU** [Jason-Rev/vscode-spell-checker#149]
mac 10.13.1
VS code 1.17.2
code spell checker 1.4.12

"Add Word to Dictionary" doesn't work anymore.
Several times before it works well, and I find these additional words on vs code preferences.
But I don't know why it doesn't work now.
<img width="620" alt="2017-11-13 11 33 30" src="https://user-images.githubusercontent.com/33610439/32705294-99c69826-c866-11e7-89c8-eb05e8bf160b.png">
<img width="391" alt="2017-11-13 11 34 45" src="https://user-images.githubusercontent.com/33610439/32705300-ac0ecfc6-c866-11e7-9417-74e30a629539.png">

I try to uninstall and re-install many times and still can not work.
Could you please help me?

**Comment by HaojinDU** [comment]
I try to uninstall and re-install many times and still can not work.

**Comment by HaojinDU** [comment]
The issue has been solved after I off and reopen the package rather than uninstall and re-install.

**Comment by Jason3S** [comment]
Thank you for opening the issue. I am sorry that it didn't work for you the first time.

One thing to note. If there is an error in the `settings.json` file as shown in your image (the red squiggle): 
![settings error](https://user-images.githubusercontent.com/33610439/32705300-ac0ecfc6-c866-11e7-9417-74e30a629539.png)

VS Code cannot load the settings file if there is an error with the `.json` format. As a result, adding words to the dictionary will fail.

The spell checker uses the build in VS Code functions to make changes to the settings. It does not directly change them.

If you have an other issues, please feel free to open a new issue.

I will close this issue if nothing further is needed.

Kind Regards,
Jason
