### ISSUE TITLE
Add new word through lightbulb does not work

### ISSUE THREAD

**Issue by yacuzo** [Jason-Rev/vscode-spell-checker#15]
Nothing seems to happen when i try to add a word through the lightbulb. 
I did work for the first word i added, but has not worked since.

Manually copying into cSpell.json is a decent workaround.

I'm running VS Code 1.3.1 and Spellchecker 0.10.6.

**Comment by yacuzo** [comment]
I tried the command, and that does not seem to work either.

**Comment by Jason-Rev** [comment]
Hello Yacuzo,

Thank you.  Can you give me a few details?

1. What operating system are you using?
1. In the directory of your project.  A file is added: .vscode/cSpell.json file is added.  Did that get added?
1. Did you open a project (directory) or a single file in vscode?  That makes a difference.  The words for a single file are stored in a different location.

Cheers,
Jason

**Comment by yacuzo** [comment]
OS: Windows 7
cSpell.json was added.
I opened a folder/directory.
I was adding words from .ts file.

Perhaps other extensions are interfering? The only ones i have which affect .ts files are 'TSLint' and Wallaby.js.

**Comment by Jason-Rev** [comment]
Hey André,

Thanks for the info.

I don't think there is a conflict with any other extensions, so no concern there.

Can you tell me what other files are in the same directory as the cSpell.json?

Is there a settings.json file?  If so, does it have a cSpell section within it?

If there is a settings.json file and there is a cSpell section, please try removing it from settings.json and putting it in cSpell.json instead.

Cheers,
Jason

**Comment by yacuzo** [comment]
In the .vscode folder I have cSpell.json, formatter.json, launch.json and settings.json. 
There is nothing cSpell-related in any of the 3 other files.

Thanks for your attention :)

**Comment by Jason-Rev** [comment]
Thank you.

I am trying to get as much information as I can to reproduce this issue.

When you add a word to the dictionary using the command or ctrl-., does the word get added to cSpell.json?  I am trying to figure out if it is writing to the cSpell.json in the project directory or in another directory.

**Comment by yacuzo** [comment]
The word is not added to cSpell.json.

**Comment by leopen-hu** [comment]
I have the same issue. like this:
![image](https://cloud.githubusercontent.com/assets/16874003/17845427/53d1affc-6874-11e6-9728-69bc4720a5c8.png).
I have 2 cSpell.json files in different path, one in **C:\Users\leopen\\.vscode**, another in **D:\Git\lion\\.vscode**.

they both created json file and added words for the first time. but then they wont't work by this way. I have to code the words in json file.

- OS: Windows 7 Service Package 1
- cSpell.json was added.
- I opened a folder in "D:\Git\lion\\.vscode", added words from .js file
- opened a file in "C:\Users\leopen\\.vscode". added words from .js file

**Comment by Jason3S** [comment]
Thank you very much for the detail explanation.

**Comment by whanwells** [comment]
The first custom word gets added successfully for me, but any words after that do not get added. Running on Windows 10 Enterprise, VS Code 1.4.0, Spell Checker 0.10.7.

**Comment by Jason-Rev** [comment]
Thank you.  I don't have Windows on my machine yet.  I still need to setup a VM to reproduce this.

**Comment by gbreeze** [comment]
I get 100% cpu workload if clicking on "Add: xxx to dictionary"

**Comment by Jason-Rev** [comment]
@gbreeze are you running in Windows as well?  If not, can you open a new issue and give as much detail as possible when this happens.

Thank you,
Jason

**Comment by Jason-Rev** [comment]
This has been fixed with 0.10.8.

**Comment by Jason-Rev** [comment]
For some reason 0.10.8 did not take.  The fix is in 0.10.10.

**Comment by gbreeze** [comment]
Nice work! This thing is getting great ;-)
