### ISSUE TITLE
cSpell.spellCheckDelayMs seems to be ignored

### ISSUE THREAD

**Issue by romines** [Jason-Rev/vscode-spell-checker#155]
`"cSpell.spellCheckDelayMs": 3000,` appears in my vsCode user settings, but this seems to have no effect on how quickly spell check flags a word as misspelled. I would prefer plenty of time to get to the end of a word without the feedback that I haven't yet spelled a valid dictionary word.

Frustratingly, when a word goes from misspelled -> correctly spelled, spell checker seems to take a significant amount of time (perhaps equal to the delay value?) to _remove_ the squiggly line that mark it as misspelled.

- Code Spell Checker 1.4.12
- VS Code:
  - Version 1.18.0
  - Commit dcee2202709a4f223185514b9275aa4229841aa7
  - Shell 1.7.9
  - Renderer 58.0.3029.110
  - Node 7.9.0
  - Architecture x64
- Ubuntu 16.04.3 LTS (xenial), kernel 4.4.0-98-generic

Thank you very much for an essential extension!

**Comment by Jason3S** [comment]
Thank you. I'll check it out.

**Comment by Jason3S** [comment]
Thank you for pointing this out. I did find an issue with the delay. I hope to have it fixed in the next release.

**Comment by Jason3S** [comment]
This was fixed in a previous release.
