### ISSUE TITLE
Extension "HTML-CSS-Class-Completion" stops German spell check to work

### ISSUE THREAD

**Issue by akalt** [Jason-Rev/vscode-spell-checker#156]
I had an issue where I could not get the German spell checker to work. After some testing I found the culprit: "HTML-CSS-Class-Completion" extension.

When this extension is activated, the German spell checker stops working; you have to restart VS Code after activating the "HTML-CSS-Class-Completion" extension.

After deactivating this extension and restarting VS Code the spell checker for German works just fine again.

**Comment by Jason3S** [comment]
Thank you. I'll see if I can figure out the issue.

**Comment by Jason3S** [comment]
Is this still an issue? I couldn't find that extension. I found HTML-LESS-Class-Completion, but it seemed to work with that one loaded.

Please re-open if you still see this issue.
