### ISSUE TITLE
Incorrectly flagged words

### ISSUE THREAD

**Issue by btracey** [Jason-Rev/vscode-spell-checker#160]
I didn't see any issues about missing words, so sorry if I don't know the policy

Words that Code Spell Check incorrectly flags as misspelled:
kurtosis
parameterized
covariance
univariate
hyperparameter

I don't know your policy on proper nouns, but Gaussian is accepted. Here are some other commonly used proper nouns that are flagged:
Wishart
Mahalanobis
Cholesky

**Comment by Jason3S** [comment]
Thank you.

The words come from two sources:
- https://github.com/Jason3S/cspell-dicts
- https://github.com/Jason3S/cspell/tree/master/dictionaries

I have been migrating the word lists from [cspell](https://github.com/Jason3S/cspell) to [cspell-dicts](https://github.com/Jason3S/cspell-dicts) when I get the time.

If you would like to contribute, please make a pull request to one of the repositories.

**Comment by Jason3S** [comment]
I have added the suggested words to SoftwareTerms. They should now be included.
