### ISSUE TITLE
Python 3.6 f-strings not parsed correctly and marked as error.

### ISSUE THREAD

**Issue by jmfederico** [Jason-Rev/vscode-spell-checker#161]
When working with python files using [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) the first word is always marked as a spelling mistake, because it is checked with the ```f'``` attached to it:

Given the following:
```python
    f'This has no mistaked.'
```
Then ```f'This``` is marked as a mistake.

**Comment by Jason3S** [comment]
Thank you. I was unaware of that.

If you are feeling adventurous, please add the pattern here: [cspell python settings](https://github.com/Jason3S/cspell-dicts/blob/master/python/cspell-ext.json#L20).
