### ISSUE TITLE
bug: no spell checking when there's no folder opened

### ISSUE THREAD

**Issue by daviehh** [Jason-Rev/vscode-spell-checker#162]
at least on macos, when just opening a file without opening any folders, there's no spell check. After open a folder the spell check goes back; verified with a clean install with just vscode-spell-checker extension and no user settings. can anyone verify? thanks!

**Comment by SimonAB** [comment]
I have the same issue here on macos, vscode v.1.18.1

**Comment by Jason3S** [comment]
Thank you. I'll investigate.

**Comment by Jason3S** [comment]
I hope to publish this fix today.
