### ISSUE TITLE
Using the extension manager it says it takes >650ms to load the plugin. This seems like a really long time 

### ISSUE THREAD

**Issue by niemyjski** [Jason-Rev/vscode-spell-checker#163]
- Extension Name: code-spell-checker
- Extension Version: 1.6.0
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 658,
		"activateCallTime": 0,
		"activateResolvedTime": 50,
		"activationEvent": "*"
	}
}
```

**Comment by trongthanh** [comment]
Ha, I'm just about to post an issue regarding this, thanks to the new Extension log in VSCode 1.19. 

My logs are: 
- Extension Name: code-spell-checker
- Extension Version: 1.6.0
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.0

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 937,
		"activateCallTime": 1,
		"activateResolvedTime": 263,
		"activationEvent": "*"
	}
}
```
Startup time nearly one second on my 2012 MBAir.

**Comment by Jason3S** [comment]
Thank you. I'll take a look.

**Comment by Jason3S** [comment]
Would you please check again, it should be much faster with version 1.6.10.
