### ISSUE TITLE
HTML and CSS files not spell checked

### ISSUE THREAD

**Issue by dgwyer** [Jason-Rev/vscode-spell-checker#170]
Just installed the extension and JS files are spell checked but HTML and CSS files seem to be ignored. No spelling errors are picked up at all in HTML and CSS files.

**Comment by Jason3S** [comment]
Thank you for reporting this.

Do you have an example? Does this still happen after restarting VS Code?

**Comment by dgwyer** [comment]
I think I had this issue when working on my Macbook a couple of weeks ago just after trying out the extension for the first time. I just tried it again on my Windows desktop machine.

I installed the extension and restarted VS Code. I then created three types of file: HTML, CSS, and JS and entered some sample code and comments. Only the JS file seemed to have spell checking active. See screenshot.

![vs-code-spell-checking-error](https://user-images.githubusercontent.com/1482075/35141350-9cf138b0-fcf2-11e7-8a48-f828bb08df50.png)

**Comment by Jason3S** [comment]
Thank you for the example.

What do you get when you right click in the `.html` and select: Show Spell Checker Configuration
![image](https://user-images.githubusercontent.com/3740137/35163117-f23ec2a8-fd45-11e7-8f43-859cb5235a1b.png)

Then choose the File Info tab:
![image](https://user-images.githubusercontent.com/3740137/35163303-89457962-fd46-11e7-9619-8d5d91c1a694.png)

**Comment by dgwyer** [comment]
Thanks Jason, that was it. Only the JS file types had spell checking on by default. This could be confusing for others though. And if I have to manually enable languages on other computers it could be a little tedious. Would it be possible to update the extension to enable all languages by default? i.e. so it's opt-out, rather than opt-in if you see what I mean?

**Comment by Jason3S** [comment]
Wow, you are right, I had thought they were enabled by default.

**Comment by dgwyer** [comment]
:)

**Comment by Jason3S** [comment]
I have turned them on by default:

![image](https://user-images.githubusercontent.com/3740137/36564515-dce98972-181d-11e8-88b4-444166027a1b.png)

**Comment by dgwyer** [comment]
Thanks Jason. 👍

**Comment by Jason3S** [comment]
Thank you for the feedback. Closing this issue.
