### ISSUE TITLE
Support for Rust

### ISSUE THREAD

**Issue by andreevlex** [Jason-Rev/vscode-spell-checker#174]
Thanks for the great extension.
Use Your extension when working with Rust. How to add support for Rust ?

**Comment by Jason3S** [comment]
I think that is a great idea!

**Comment by andreevlex** [comment]
Do I understand correctly? I need to do https://github.com/Jason3S/cspell-dicts PR ?
The requirements for naming are the files?

**Comment by Jason3S** [comment]
That would be ideal.

Each programming language dictionary is made up of a list of keywords and common library names and functions.

The idea is to be able to turn off the English dictionary and program another language like Spanish or Russian.

A keyword file like `rust.txt` would be fine. Yoeman will generate everything else. If you got the list of words from a copyright source, please include a reference to its license.

If you get stuck, let me know. I can generate the dictionary if necessary.

Thank you for helping.

**Comment by andreevlex** [comment]
https://github.com/Jason3S/cspell-dicts/pull/20

**Comment by Jason3S** [comment]
I have added your wordlist to the dictionary. Let me know how well it works.

**Comment by andreevlex** [comment]
work fine
