### ISSUE TITLE
JSDoc directive "@memberof" is detected as a typo

### ISSUE THREAD

**Issue by Hendrik410** [Jason-Rev/vscode-spell-checker#177]
In TypeScript, the `@memberof` directive of JSDoc is detected as a typo as seen on this picture:
![image](https://user-images.githubusercontent.com/11255608/35974603-011a3ad4-0cda-11e8-8082-ba457d3f1bff.png)

I think spellcheck should be disabled for such directive, shouldn't it?

Greetings,
Hendrik

**Comment by Jason3S** [comment]
It makes sense that it should be part of the JS and TS dictionary.

The word is just missing from the JS dictionary.

I'll add it.

**Comment by Jason3S** [comment]
I added it to the [`typescript`](https://github.com/Jason3S/cspell/blob/master/dictionaries/typescript.txt#L317) word list.
