### ISSUE TITLE
Find all spelling errors across all files in a project

### ISSUE THREAD

**Issue by laggingreflex** [Jason-Rev/vscode-spell-checker#178]
It would be really useful to find all spelling errors in the entire project at once. 

This is especially handy when using this plugin on a new project.

It could have its own sidebar listing all the files that contain spelling errors, much like finding text in files.

**Comment by Jason3S** [comment]
How about using a command line tool: [cspell](https://github.com/Jason3S/cspell)?

The `cspell` library powers this extension.

**Comment by laggingreflex** [comment]
That is awesome! Thanks! Feel free to close as it served my purpose, but I still think VSCode integration could be nice.. Maybe something for the future.

**Comment by Jason3S** [comment]
Yes it is a possible future enhancement.
