### ISSUE TITLE
Recognise is not valid in UK dictionary

### ISSUE THREAD

**Issue by dolanmiu** [Jason-Rev/vscode-spell-checker#182]
For some reason this word is not recognised (lol :joy:)

https://en.oxforddictionaries.com/definition/recognize

https://forum.wordreference.com/threads/recognise-recognize-realise-realize-ise-ize.217843/

**Comment by Jason3S** [comment]
Thank you. I just checked the dictionary. `Recognise` is there.

It seems the UK dictionary is not turned on.

If you right click in the file where you see problem, like the image below:

![image](https://user-images.githubusercontent.com/3740137/36350069-3734c1f2-1491-11e8-89ce-04b6ea31e1bb.png)

Choose `Show Spell Checker Configuration Info`

It will bring up a screen that looks like this (the languages listed might vary):
![image](https://user-images.githubusercontent.com/3740137/36350086-90b77d1e-1491-11e8-8309-0b8cf433f7fa.png)

If you turn on English-United Kingdom, it should fix the issue.

**Comment by dolanmiu** [comment]
Ok, I do believe it is a bug

Why is recognise not valid, but colour is?

![image](https://user-images.githubusercontent.com/2917613/36377018-4ee1743a-156d-11e8-8361-9d0c775715a1.png)

Here is my settings:

![image](https://user-images.githubusercontent.com/2917613/36377049-6ec8058e-156d-11e8-9148-b3ad72ebdc01.png)

I have a `cSpell.json` which has both `"language": "en-US, en-UK"`

**Comment by Jason3S** [comment]
`colour` must be in one of the other dictionaries that is loaded.
`en-UK` is not a valid local. `en-GB` is the local for the United Kingdom.
If you click the **English - United Kingdom** switch, it will add it to your cSpell.json file.
