### ISSUE TITLE
All CAPS words in LaTeX

### ISSUE THREAD

**Issue by James-Yu** [Jason-Rev/vscode-spell-checker#187]
Current extension does not distinguish `[A-Z]` from `[a-z]`, which is reasonable in plain text. However, people tend to invent their own acronyms and re-use them across literature. Regexr such as `^[A-Z]{2,}$` won't properly exclude such words.

It seems that (though I did not dig into the code) the extension `toUpperCase` before `reg.exec`. The sequence IMO should be inverted to properly respect caps in regex while not influencing the language server.

**Comment by Jason3S** [comment]
When I get the chance, I'll take a look. Off the top of my head, `ig` flags are automatically added to each regex. You can prevent this by fully specifying the regex with the flags you want: `"/[A-Z]{2,}/g"`

**Comment by James-Yu** [comment]
Awesome! `/[\\W\\d][A-Z]{2,}[s\\W\\d]/g` is working good for me to ignore the acronyms.
