### ISSUE TITLE
[Feature Request] Combine repeated unknown words in Problems tab

### ISSUE THREAD

**Issue by jameshamm** [Jason-Rev/vscode-spell-checker#194]
Currently, if a word is repeatedly misspelled it will appear up to 4 times in the Problems tab.

![step0004](https://user-images.githubusercontent.com/10179936/36914142-365e171c-1e44-11e8-8f44-32f3b0efa477.png)

Would it be possible to combine these into one issue?

P.S. Why does it only display the first 4 occurrences of a repeated issue?

**Comment by Jason3S** [comment]
> Would it be possible to combine these into one issue?

VS Code controls how issues are shown in the problem window. The extension doesn't have any control. Being able to collapse duplicate issues would be a VS Code feature request.

> P.S. Why does it only display the first 4 occurrences of a repeated issue?

Thank you for bringing this up. It looks like I forgot to expose the setting. It is there, just hidden. When I get the chance, I'll put a patch out.

To set it:
In the VS Code settings:

```
"cSpell.maxDuplicateProblems": 5,
```

In a cspell.json file:

```
"maxDuplicateProblems": 5,
```

**Comment by Jason3S** [comment]
I have fixed the documentation and this will go out in the next release.
