### ISSUE TITLE
add to dictionary right click no longer working

### ISSUE THREAD

**Issue by BramGruneir** [Jason-Rev/vscode-spell-checker#20]
It now shows up as "" and when clicked doesn't add anything to the dictionary anymore.

![screen shot 2016-10-11 at 16 23 50](https://cloud.githubusercontent.com/assets/1614265/19287313/376363ba-8fcf-11e6-98cc-644bb34ee13b.png)

**Comment by Jason-Rev** [comment]
I think this is related to the VSCode update.  I'll check today.

**Comment by Jason-Rev** [comment]
I just verified that it is a bug introduced by the latest VSCode update.  I'll see if I can find a fix.

**Comment by Jason-Rev** [comment]
I have just pushed the fix to VSCode Marketplace, version 0.10.12.  Please download it and verify.
