### ISSUE TITLE
Add an option to disable scrollbar marks

### ISSUE THREAD

**Issue by brunetton** [Jason-Rev/vscode-spell-checker#200]
Hi,

I'm using this great plugin everyday and I love it ! I think the only default I find is that the scrollbar is very "crowded" with marks from linter, git modifications, and spell-check marks. I don't need spellcheck marks in scrollbar and I'd like to disable it, if it is possible.

Thanks

**Comment by brunetton** [comment]
Thanks !

**Comment by fega** [comment]
@Jason3S There is any way to change the color of this marks? it would be a matter just to change the color to the selected theme one.
