### ISSUE TITLE
Asciidoc support

### ISSUE THREAD

**Issue by lferrao** [Jason-Rev/vscode-spell-checker#205]
Is Asciidoc support part of the roadmap for this extension?

**Comment by lferrao** [comment]
I didn't realize I could just enable it, I thought the language itself wasn't supported. There's some minor issues with things that it tries to spell check and shouldn't, but overall it seems perfectly usable. Thanks a lot!

**Comment by Jason3S** [comment]
If you have some examples of things that do not work as expected, please open an issue.
