### ISSUE TITLE
Add to dictionary does not work

### ISSUE THREAD

**Issue by janhancic** [Jason-Rev/vscode-spell-checker#21]
Hi,

the "add to dictionary" functionality seems to not work. See this for reference: http://recordit.co/rONUAa1Zr4

Usually if I close and reopen the file after adding a word to the dictionary it works, but in this case it doesn't.

I'm on a mac and latest vstudio insiders version.

**Comment by Jason3S** [comment]
Thank you for the report.  I'll check it out.

**Comment by Jason3S** [comment]
It is currently working for the VS Code stable release.  I'll download the insider version and check it out.

**Comment by Jason3S** [comment]
I am having trouble reproducing this.  I am on insider version: 1.7.0-insider.

Are you working with an individual file or do you have a directory open?  Where the cSpell.json file is stored is different.

**Comment by Jason3S** [comment]
This is fixed with 0.10.13.

**Comment by janhancic** [comment]
Amazing, thanks!
