### ISSUE TITLE
spell checker checks spelling on git version of files

### ISSUE THREAD

**Issue by babysnakes** [Jason-Rev/vscode-spell-checker#214]
Hi,

I'm not sure what exactly happens but it seems that every file I work on (which has spell errors that are locally ignored by workspace dictionary) also displays spell errors in some form of git version. Best thing I can do is attach a screenshot, please check the name of the file where errors are indicated (ends with `go.git`) and path of file (starts with `git:/Users/...`

Not even sure what info to provide in order to help debug this error. Please let me know what info you need and I'll gladly provide it.
<img width="750" alt="screen shot 2018-04-22 at 8 26 21" src="https://user-images.githubusercontent.com/31975/39091869-406d3d24-4607-11e8-9960-9e6a29740390.png">

**Comment by Jason3S** [comment]
Thank you. I'll take a look. 
Which git extensions do you use?

Whenever an extension opens a file (even in the background) the spell checker gets notified and will check the spelling. The spell checker should ignore files of the wrong type.

**Comment by babysnakes** [comment]
Wow, that was fast 😃, The git related extensions I have are:

* Git History (0.4.0)
* Git History Diff (1.1.3)
* GitLens (8.2.3)
* Run git difftool (0.0.5)

Thank you very much. Please let me know if you need anything else.

**Comment by Jason3S** [comment]
I found this issue. If you update the extension to version 1.6.9. the issue should be fixed.

**Comment by babysnakes** [comment]
Wow that was fast 😃 , Thanks.

**Comment by Jason3S** [comment]
It was a regression introduced in the last update.
