### ISSUE TITLE
pretty intense startup delay

### ISSUE THREAD

**Issue by kapral18** [Jason-Rev/vscode-spell-checker#216]
- Extension Name: code-spell-checker
- Extension Version: 1.6.9
- OS Version: Darwin x64 17.5.0
- VSCode version: 1.22.2

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 914,
		"activateCallTime": 0,
		"activateResolvedTime": 86,
		"activationEvent": "*"
	}
}
```

**Comment by Jason3S** [comment]
Thank you. Related to: #163

**Comment by Jason3S** [comment]
The load time should now be much lower. It is still not perfect, but much better.

**Comment by kapral18** [comment]
Thanks for quick response.
