### ISSUE TITLE
Missing Words: Collider

### ISSUE THREAD

**Issue by rakkarage** [Jason-Rev/vscode-spell-checker#217]
Collider is marked as a misspelling in English?
Works in Spell Right and other English dictionaries.
Fine. I can add to dictionary. Just wondering...
Thanks.

**Comment by Jason3S** [comment]
Thank you. I'll add it. It is missing from the original word list: [Hunspell English Dictionaries](http://wordlist.aspell.net/hunspell-readme/)

**tldr;** the spell checker uses the Hunspell dictionary to build a word list.

The `.dic` entry for collide seems to be missing the `R` rule: 
```
collegiate
collide/DSG
collie/RSMZ
```
