### ISSUE TITLE
Next misspelling

### ISSUE THREAD

**Issue by allenryb** [Jason-Rev/vscode-spell-checker#219]
Is there some method to quickly locate the **next misspelling** word?

This may be a trivial problem. But I haven't found any answer.

Thanks in advance!

**Comment by Jason3S** [comment]
It uses the standard VS Code keys:
* `Goto Next Problem`: F8
* `Goto Previous Problem`: SHIFT-F8

Then you can use CTRL-. or CMD-. to bring up a list of suggestions.

**Comment by allenryb** [comment]
Thanks for your suggestion!
