### ISSUE TITLE
When you add words. They don't update on the screen.

### ISSUE THREAD

**Issue by pmkary** [Jason-Rev/vscode-spell-checker#22]
This screenie should tell the whole story:

![bug](https://cloud.githubusercontent.com/assets/2157285/19413576/355c42ea-933e-11e6-84e9-f2f82f743e30.gif)

I've had this problem since months ago. So I thought why not mentioning it

**Comment by Jason3S** [comment]
Thank you.  It is clearly not working as you would expect.

Can you give me a bit more information about your setup?
Which version of VS Code are you running?
Which version of the cSpell plugin are you using?
Which OS version are you on?
Do you have a single file open or a folder?

**Comment by pmkary** [comment]
Okay this is my full settings:
```JSON
{
	"editor.fontSize": 				13,
	"editor.lineHeight":            26,
	"editor.fontFamily":            "Hasklig-Medium",
	"editor.tabSize": 				4,
	"editor.wrappingColumn": 		90,
	"editor.wrappingIndent":        "same",
	"editor.quickSuggestionsDelay": 0,
	"editor.renderWhitespace": 		false,
	"editor.insertSpaces": 			true,
	"cSpell.enabledLanguageIds": [
		"csharp",
		"javascript",
		"javascriptreact",
		"markdown",
		"plaintext",
		"text",
		"typescript",
		"yml",
		"ruby",
		"pageman",
		"html"
	],
	"cSpell.userWords": [
		"Pouya",
		"Kary",
		"karyfoundation",
		"Arendelle",
		"arendelle",
		"pouya",
		"kary",
		"intactus",
		"calculat",
		"hedron",
		"gerda",
		"levitator",
		"Pageman"
	]
}
``` 

And well I use macOS El Capitan with the latest version of both vscode and cSpell. Most of the projects are on github. you may check [kf's org](https://github.com/karyfoundation). all of the TypeScript, JavaScript projects are done with cSpell

**Comment by Jason3S** [comment]
Have you tried closing all your VS Code windows and checking the Activity Monitor to make sure all VS  Code instances have stopped?

**Comment by Jason3S** [comment]
Please try updating the spell checker to the latest version.

**Comment by pmkary** [comment]
Oh thank you! It's fixed and very cool now!

Thanks a lot for the great tool! Having a spell checker for me is something really really cool!!
