### ISSUE TITLE
Missing words: rebasing, composable, changeset

### ISSUE THREAD

**Issue by hzhu** [Jason-Rev/vscode-spell-checker#222]
First off thanks @Jason-Rev for this awesome tool 💯!

I wanted to see if you were okay with adding these common software words to the dictionary so that they do not get recognized as unknown words.

1) "rebasing"
2) "composable"
3) "changeset"

Note: "changeset" might be a relatively new word that was introduced when version control software became popular. References to this word can be found [here](https://en.wikipedia.org/wiki/Changeset) and on git's documentation [here](https://git-scm.com/docs/gitglossary#gitglossary-aiddefchangesetachangeset).

<img width="585" alt="screen shot 2018-05-13 at 10 16 11 pm" src="https://user-images.githubusercontent.com/1811365/39979455-4ccffc96-56fb-11e8-863a-c7f44ac2ec06.png">

**Comment by Jason3S** [comment]
Please feel free to do a pull request here: [software terms dictionary](https://github.com/Jason3S/cspell/blob/master/dictionaries/softwareTerms.txt)
