### ISSUE TITLE
Feature: Disable spell checking for code block via comment

### ISSUE THREAD

**Issue by codeandcats** [Jason-Rev/vscode-spell-checker#223]
As a developer
I would like the ability to disable spell checking for a section of code
So that I can ignore text without adding them to the dictionary

Here's an example of a time I don't want to add a "spelling mistake" to the dictionary

<img width="379" alt="screen shot 2018-05-17 at 9 50 15 am" src="https://user-images.githubusercontent.com/6035934/40149746-be078068-59b8-11e8-9a89-52f5201e2b13.png">

It would be preferable if I could simply add a comment to instruct when the spell checker should stop checking and when to resume, similar to how you can [disable rules in eslint](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).

e.g. To disable spell checking for a section of code:

```javascript
// code-spell-checker:disable
const secret = 'lkajsdf98u23oij4lk23j4lkjasdf';
const salt = 'lk2j092u34oiju2lk43j28934u';
// code-spell-checker:enable
```

Or to disable checking for a single line:

```javascript
// code-spell-checker:disable-next-line
const secret = 'lkajsdf98u23oij4lk23j4lkjasdf';
```

**Comment by Jason3S** [comment]
Please see: [Enable Disable Checking Sections of Code](https://github.com/Jason-Rev/vscode-spell-checker/tree/master/client#enable--disable-checking-sections-of-code) (Which seem slightly out of date, since the library supports next-line as well: [cspell library](https://github.com/Jason3S/cspell#enable--disable-checking-sections-of-code))

**Comment by codeandcats** [comment]
Awesome, sorry I missed this and thanks for pointing me in the right direction. Great extension btw! 👍
