### ISSUE TITLE
include Code Spell Checker in Docs Authoring Pack

### ISSUE THREAD

**Issue by meganbradley** [Jason-Rev/vscode-spell-checker#229]
Hello @Jason-Rev,

I'm a PM on the docs.microsoft.com team at Microsoft, working on authoring tools for content contributors. My team recently shipped the [Docs Authoring VS Code extension pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack), including our own Markdown authoring extension as well as David Anson's popular Markdown linter and a preview service.

We're shipping our next extension pack release in the next week or so, and would like to bundle your spellchecker as part of the pack and include it in our docs.microsoft.com blog post announcement.

Please let us know if you have any concerns about this or any particular description of the spellchecker you'd like us to include in the blog post. The blog post for our last release is here for reference:

https://docs.microsoft.com/en-us/teamblog/docs-extension

Thanks!
Megan Bradley, PM
docs.microsoft.com team

**Comment by Jason3S** [comment]
Hello Megan,

I am honored that you would want to include the spell checker in your bundle. Please feel free to do so.

Kindly,
Jason

**Comment by meganbradley** [comment]
Thank you!

**Comment by Jason3S** [comment]
Glad I could help.
