### ISSUE TITLE
Enable/Disable in comments

### ISSUE THREAD

**Issue by lucamartinetti** [Jason-Rev/vscode-spell-checker#24]
It would be nice to have a syntax in comments to enable / disable the spell checker. 

Something similar to tslint.

``` javascript
/* spell-checker:disable */
const foo = "Thiz nott checkedd";
/* spell-checker:enable */
```

**Comment by Jason3S** [comment]
I think this is a good idea.  I have to think how best to do this.

**Comment by Jason3S** [comment]
This is in 0.12.2

**Comment by Jason3S** [comment]
Thank you for your suggestion.
