### ISSUE TITLE
cSpell hangs and high cpu usage

### ISSUE THREAD

**Issue by gbuktenica** [Jason-Rev/vscode-spell-checker#240]
After an upgrade to vscode 1.25.0 I am getting the same issue listed here:
https://github.com/Jason-Rev/vscode-spell-checker/issues/78

Action taken to attempt resolution:
Uninstalled all extensions and Uninstalled vscode. Installed vscode with only vscode-spell-checker.
Tested with vscode insiders and it is showing the same behavior.
User settings file is now empty.

**Comment by gbuktenica** [comment]
Windows 10.0.15063 build 15063
I am using VS Code 1.25.0 and I had no problems with 1.24.0 or previous.
Python, PowerShell and Markdown primarily.
I have been opening Git projects. I have just tested a new mark down file not in a project and the problem did not occur.

**Comment by gbuktenica** [comment]
I am getting interesting behaviour now. With my production copy of vscode I have closed my project and restarted vscode. The problem has gone away, I can open single files and project and spell checking works.
Will my insiders copy of vscode I have not closed my project and the issue is still occurring each time it is opened.

**Comment by Jason3S** [comment]
VS Code sometimes doesn't shut everything down when it updates. So, processes can still be running, which cause problems.

A full restart of VS Code insiders should fix the issue.

**Comment by gbuktenica** [comment]
Yes, a full restart is the solution.
