### ISSUE TITLE
Add some missing terms

### ISSUE THREAD

**Issue by pzmarzly** [Jason-Rev/vscode-spell-checker#258]
After using the extension for a while, I found some linted words:

- [x] alloc - short for `allocate`, used in Rust (`std::alloc`)
- [x] autostart
- [x] ctrlc
- [x] deallocate
- [x] deserialize
- [x] keycode
- [x] millis - short for `milliseconds`, used in Rust (`std::time::Duration::from_millis`)
- [x] mutex
- [x] serde - serialization library for Rust
- [x] stringify - macro used in Rust
- [x] toml - TOML language, often used as config files
- [x] toolchain
- [x] wacom - Wacom device manufacturer
- [x] xdotool, xinput, xmodmap, xserver - X11 (display server for Linux) binaries & utilities
- [x] yakuake - terminal emulator for Linux

Obviously some of them should go to `softwareTerms` and some to `rust` dictionary (or maybe not? after all, someone can mention `serde` in README).  Maybe some new dictionaries should be created (brand names, program names etc.)?

**Comment by Jason3S** [comment]
Thank you.

At the moment, there are two primary places for dictionaries:
* [cspell-dicts](https://github.com/Jason3S/cspell-dicts)
* [cspell imbedded dictionaries](https://github.com/Jason3S/cspell/tree/master/dictionaries)

New dictionaries are added in [cspell-dicts](https://github.com/Jason3S/cspell-dicts)
