### ISSUE TITLE
Overriding `statusBar.debuggingForeground` and `statusBar.noFolderForeground` color 

### ISSUE THREAD

**Issue by Plac3hold3r** [Jason-Rev/vscode-spell-checker#269]
Code Spell Checker always defaults to using the user's theme's [`statusBar.foreground`](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/src/statusbar.ts#L17) color. This can cause an issue if the theme makes use of a different `statusBar.debuggingForeground` color for when in debugging state.

Default status bar
![image](https://user-images.githubusercontent.com/13716738/45258438-b1e8a100-b3b7-11e8-90b1-6586fbc1e3a7.png)

Debugging status bar
![image](https://user-images.githubusercontent.com/13716738/45258391-f4f64480-b3b6-11e8-98c6-2269127dec2c.png)

This would also have the same effect on a custom theme color usage for `statusBar.noFolderForeground` getting overridden.

If I remove the `sbCheck.color = new ThemeColor('statusBar.foreground');` it seems to honor the theme's color options. Is there a particular reason to force the usage of `statusBar.foreground`?

**Comment by Jason3S** [comment]
Thank you for looking into this. I'll take a look to see why it might be used. When that code was written, there was only `statusBar.foreground`.

**Comment by Plac3hold3r** [comment]
@Jason3S  thanks. I forgot to include I was testing against Visual Studio Code version 1.27.1
