### ISSUE TITLE
Regex Ignore

### ISSUE THREAD

**Issue by bsell93** [Jason-Rev/vscode-spell-checker#27]
Is it possible to add words to our `settings.json` that are regex and it ignores words that match it?
For example `new Guid("........-....-....-....-...........")` or any regex that is desired.
So settings something like

``` json
"cSpell.words": [
    "new Guid(\"........-....-....-....-...........\")"
]
```

**Comment by kentcdodds** [comment]
This may also be handy for another thing I was about to suggest. I don't want URLs to be spell checked. For example:

<img width="537" alt="screen shot 2016-10-31 at 9 32 16 am" src="https://cloud.githubusercontent.com/assets/1500684/19860037/f4c4f298-9f4c-11e6-95f6-2cdc38e641cb.png">

**Comment by Jason3S** [comment]
I am looking into a more general solution.  That would also solve #3 and possibly #24.

**Comment by thorn0** [comment]
I also would like to have this feature to disable spell-checking for CSS colors like `#cccccc`.

**Comment by Jason3S** [comment]
With 0.14.0, it is now possible to define RegExp to be ignored:

```javascript
"cSpell.ignoreRegExpList: [
    "0x[0-9A-F]+",
    "#[0-9A-F]+",
    "file:\\S+"
]
```

or you can add as a comment in the source file:

```javascript
// cSpell:ignoreRegExp 0x[0-9A-F]+
// cSpell:ignoreRegExp #[0-9A-F]+
```

**Comment by Jason3S** [comment]
If you want enhancements to how this works, please open a new issue and refer to this one.

**Comment by jens1o** [comment]
Really helpful! Thanks 😄

**Comment by jreljac** [comment]
Is it possible to ignore anything starting with `$`?

I've tried a number of different regex options with no luck, even tried getting help on StackOverflow: https://stackoverflow.com/q/49386209/99401

**Comment by Jason3S** [comment]
I answered it on stackoverflow:

```
"cSpell.ignoreRegExpList": [
    "^\\$.+"
]
```

The `.+` at the end of the string is necessary to match till the end of the line.

**Comment by jreljac** [comment]
Thanks Jason...

That works...unless the line is indented, then it does not work.
$fullpath = $path . '/test/';
shows that fullpath is spelled wrong.

If I add what you recommended to my user settings file it works but if I
have
$fullpath = $path . '/test/'; (with a leading tab) it sill shows fullpath
as spelled wrong.
$fullpath = $path . '/test/'; (with one leading space) does the same.

I'm guessing it looks at the entire line...?
Jason

**Comment by jreljac** [comment]
Jason,

Perfect!  Thanks for the help on this.

J-

**Comment by YangRongAtGit** [comment]
Hello Jason, 
I am trying to ask the spell checker to ignore the keywords `Clarinox` and `Txts`. In the code, with a case insensitive fashion, I have things like ClarinoxStructure or Clarinox_Variable.

So I add the following settings in the settings.json
```
"cSpell.ignoreRegExpList": [
        "(?i)(?<=\\s|^|\\W|\\w)(Clarinox|Txts)(?=\\s|$|\\W|\\w)"
    ],
```

But it seems the checker still can pick those keywords. Any suggestions?

Thanks
