### ISSUE TITLE
Checker is picking half words

### ISSUE THREAD

**Issue by jpidelatorre** [Jason-Rev/vscode-spell-checker#271]
Lately the spell checker has been picking some half words.
- _constructor_ picked as _constr_
- _individual_ picked as _individ_
- _Virtual_ picked as _Virt_
- _latitude_ picked as _latit_

And in one particular instance _SidemenuComponent_ became _omponent_.

It's not really an important matter, but I thought it was worth noting as there may be a bigger underlying problem.

**Comment by Jason3S** [comment]
@jpidelatorre is this still an issue?

**Comment by jpidelatorre** [comment]
@Jason3S Yes, it still is. It still appears here and there even with a new installation on a different computer.

**Comment by Jason3S** [comment]
Can you give me more details on when it happens? Does it fix itself?
What value are you using for the spell check delay?

![image](https://user-images.githubusercontent.com/3740137/57189724-62408200-6f12-11e9-960c-c6c8e88ae399.png)

**Comment by jpidelatorre** [comment]
The delay is set at 200ms. I don't think that is the problem because the issues appear every time I input one of the glitched words. It makes no difference whether I type them, paste them, or autocomplete them.

Even in fringe scenarios: If I have a line that reads "Sidemenu Component", the checker raises no issues. If I erase the space in between words, the checker picks "omponent" as an error. Same thing if I drag and drop the words together.

By the way, the checker has no problem with the word "component" other than when the letter "U" precedes it. Also, "constr" gets picked in "construct" and "constructor" but not in "constraint" or "constrict".

Coming to think of it, the errors always have something to do with the letter "U".

Oh, and, they never fix themselves. I've learned to accept I'll get errors everywhere.

**Comment by Jason3S** [comment]
Are you using `ignoreRegExList`? It is acting like `u` is being selected to be ignored. What kinds of files are you editing?

**Comment by jpidelatorre** [comment]
That was exactly the problem. I had this in the `ignoreRegExList`:
```regexp
(0x|\\u)[a-f0-9]+
```

I don't remember having that set but, I must have it to use Javascript Unicode sequences. I fixed it by escaping the backslash.

**Comment by jpidelatorre** [comment]
I'll close this and walk back home in shame. Thank's a lot, @Jason3S. I couldn't have solved it without your guide.
