### ISSUE TITLE
Every word is spelled incorrectly in markdown files

### ISSUE THREAD

**Issue by carsonkk** [Jason-Rev/vscode-spell-checker#276]
I have multiple markdown files in a project where, when they're closed, the files aren't marked as having any issues when viewed in the Explorer. When they're open, however, the files are marked red in the Explorer as having errors, and in the files themselves every word (that isn't in a code bracket) is marked with a red underline, thus rendering the plugin useless for any actual spell checking. This is with default settings in a freshly install copy of vscode/the spell-checker plugin. Could this be an issue with a missing dictionary? I've tried uninstalling/reinstalling vscode as well as the plugin but it didn't seem to be an issue with either being out of date.

![screenshot from 2018-10-11 10-37-19](https://user-images.githubusercontent.com/10569071/46822934-a9caab00-cd41-11e8-8ab2-387d87e90068.png)

**Comment by Jason3S** [comment]
Wow, that can be very annoying. It is not normal for it to work that way.

There are a few things to check:

1. This can be caused if there is an error in your `vscode/settings.json` file. Open Preferences and make sure VS Code doesn't give any warnings.

1. Bring up the Spell Checker Configuration: `F1 -> Show Spell Checker Configuration`
![image](https://user-images.githubusercontent.com/3740137/46855919-515ce180-ce05-11e8-8471-b56cdb43afda.png)

Check to make sure the English dictionary is turned on:
![image](https://user-images.githubusercontent.com/3740137/46856002-97b24080-ce05-11e8-8173-b99102d10feb.png)

Please let me know if that works for you.

**Comment by carsonkk** [comment]
No errors/warnings in my settings.json file (and the project doesn't have any local workspace-specific settings). I checked the panel in your screenshot and it looks like this:
![screenshot from 2018-10-13 14-47-04](https://user-images.githubusercontent.com/10569071/46910293-e7246980-cef6-11e8-9e01-5021bdf5b2b5.png)
Tried messing with different settings for it and reloading but no difference

**Comment by carsonkk** [comment]
Also the english dictionary is definitely enabled for markdown files so I'm not sure why they're the only file type giving me this issue.
![screenshot from 2018-10-13 14-51-28](https://user-images.githubusercontent.com/10569071/46910324-92352300-cef7-11e8-9df4-aede5c4dc821.png)

**Comment by carsonkk** [comment]
So for better or worse this ended up resolving itself after another update to VSCode. Not sure what was up, if anyone comes across this later on:
- Update VSCode if you haven't already
- Make sure you don't have any other spell checking libraries installed
- Try uninstalling/reinstalling the plugin
- Once you save your settings, try uninstalling/reinstalling vscode, basically do whatever you can to isolate the problem
