### ISSUE TITLE
Add delay configuration option

### ISSUE THREAD

**Issue by kentcdodds** [Jason-Rev/vscode-spell-checker#28]
Thanks for this tool. It's _already_ caught a few errors!

I'm a pretty quick typist, but not quick enough :) I'd really love to be able to specify a delay before the spell checking happens so I don't see underlines while I'm trying to finish up a world. For example:

![spellcheck](https://cloud.githubusercontent.com/assets/1500684/19860367/06efff52-9f4e-11e6-9eae-6ad6bdfa0ea5.gif)

**Comment by Jason3S** [comment]
I never thought about that.  It is easy enough to make the debounce configurable.

**Comment by Jason3S** [comment]
I have added a setting: spellCheckDelayMs.  It defaults to 50ms.  But you can make it as high as you like.  Maybe 2000 for a 2 second delay.

This change is in 0.12.0.
