### ISSUE TITLE
Upgrade to VS Code's webview API

### ISSUE THREAD

**Issue by mjbvz** [Jason-Rev/vscode-spell-checker#281]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by Jason3S** [comment]
That is excellent news. I will take a look during the Thanksgiving week.

**Comment by mjbvz** [comment]
Just a heads up: in VS Code 1.32 (the February update), using the previewHtml command will show an alert to the user, although the command should still work. We plan to remove the command entirely with VS Code 1.33 (March update)

**Comment by Bernd-L** [comment]
Just a reminder: The alert is here:
>Extension 'streetsidesoftware.code-spell-checker' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by Contrapuntist** [comment]
Any progress with updating the extension? Got the same message today.

**Comment by Jason3S** [comment]
Thank you for the reminder.
I have been busy with creating a new settings screen. I'm almost done.

**Comment by chigix** [comment]
Visual Studio Code is alerting about this usage of deprecated api these days since the latest version update. Waiting for the release ❤

**Comment by ExE-Boss** [comment]
You can see the&nbsp;progress in&nbsp;the&nbsp;[webview](https://github.com/Jason-Rev/vscode-spell-checker/tree/webview)&nbsp;branch.

**Comment by Jason3S** [comment]
This is fixed with 1.7.0
