### ISSUE TITLE
Quick actions stop functioning after clicking result form Problem window

### ISSUE THREAD

**Issue by nschonni** [Jason-Rev/vscode-spell-checker#283]
Issue Type: <b>Performance Issue</b>

Highlight a result from the problem window doesn't show the quick actions/lightbulb. Using cmd+. or control+. just causes a editor window progress bar with now menu. Closing the editor window also still leaves the flagged problems stuck in the Problem window
Started happening after the 1.29.0 release and may be a more general 

Extension version: 1.6.10
VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   21	   115	 77193	code main
    3	    33	 77194	   gpu-process
    0	   213	 77195	   window (piecewise-constant-distribution-class.md — cpp-docs)
    0	   115	 77265	     extensionHost
   99	   123	 77334	       electron_node server.js 
    0	    33	 77373	       /Users/nschonni/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.954/dotnet_modules/vsls-agent --autoexit --pipe d199dba506e04a8cbcc7c79fd7316965 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    25	 77266	     watcherService
    0	     0	 77268	     /bin/bash -l
    0	    33	 77331	     searchService
    0	    66	 77267	   shared-process
    8	   147	 77574	   window (Issue Reporter)
    7	     0	 77576	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (piecewise-constant-distribution-class.md — cpp-docs)
|    Folder (cpp-docs): 12676 files
|      File types: md(9539) cpp(2252) h(359) png(267) gif(120) PNG(32) idl(22)
|                  vcxproj(16) filters(16) xaml(11)
|      Conf files: sln(8) settings.json(1);
```

</details>

**Comment by Jason3S** [comment]
Thank you. I'll see if I can reproduce it.

**Comment by Jason3S** [comment]
This should be fixed. If it is still happening, please let me know.
