### ISSUE TITLE
Doesn't work with Code Insiders 

### ISSUE THREAD

**Issue by NKjoep** [Jason-Rev/vscode-spell-checker#294]
Hello 👋 

I use Code Insiders and this plugin doesn't work. All I know is any command/feature returns this message `command 'cSpell.displayCSpellInfo' not found`

So, the plugin seems _disabled_ and when I try to recall any of its functions -->
![image](https://user-images.githubusercontent.com/286066/50976765-109e6280-14f1-11e9-846e-5cb3b7c683d4.png)

all I get is that message. I couldn't find any other error message in the vscode logs.

Is it a known problem? Any help is appreciated 🙏 

Thanks!

**Comment by NKjoep** [comment]
I did this already a few times, in this exact order.

is there something else I should consider?

**Comment by Jason3S** [comment]
Yes that can be very frustrating.
I just now updated to Code Insiders: 1.31.0. It seems to be working fine.

When you uninstall the extension, VS Code does not fully remove it. To force it to be downloaded again, you have to delete it from the extension directory.

On my machine it is here:
```
~/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.6.10/
```

Make sure the extension is uninstalled, then remove the entire directory. Installing it again, should work.

**Comment by NKjoep** [comment]
oh yes finally :) 
Removing the mentioned directory worked, thanks!
