### ISSUE TITLE
Option to enable/disable INFO output at the VSCode 'Problem' panel

### ISSUE THREAD

**Issue by gbreeze** [Jason-Rev/vscode-spell-checker#30]
![image](https://cloud.githubusercontent.com/assets/1906169/20301118/58c8ddc8-ab22-11e6-8417-cb0860172bb5.png)

**Comment by Jason3S** [comment]
Hmm, I am not sure how to do that.  VSCode does that automatically when underlines are added to words.  If you find a way in the VSCode docs, please let me know.

**Comment by BillDenton** [comment]
+1
It would be useful for them to be indicated in the source code by underlines, but not show in problem window. It hides compiler messages.

**Comment by Jason3S** [comment]
Something that might help this issue with the release of 0.14.0.
* Turn on `"cSpell.allowCompoundWords": true`
  This will help with all of the double word errors like "contextmenu".

**Comment by Jason3S** [comment]
Also with 0.14.0, the number of problems shown have been reduce.  At max, duplicate issues will only be shown 5 times. #46

**Comment by Jason3S** [comment]
The number of issues show in the output panel should have been reduced.  With some of the recent releases.  Is this still a major issues?  I don't have a lot of control of when things show in the panel or not.

The recent release reduced the number of issues shown by filtering out issues when a tab is closed and by not showing issues that were in hidden editors opened by other extensions.

**Comment by gbreeze** [comment]
True, thanks Jason

**Comment by jessycormier** [comment]
Is there still no way to "disable" reporting in the problems panel ?
