### ISSUE TITLE
100% CPU usange (single thread)

### ISSUE THREAD

**Issue by tecosaur** [Jason-Rev/vscode-spell-checker#303]
I have one file being spellchecked, with 150 lines. Specifically, it's https://github.com/tecosaur/BMC/blob/master/demo.tex. This issue is apparent immediately after restarting vscode.

![image](https://user-images.githubusercontent.com/20903656/52526443-b5c87880-2cf3-11e9-82d9-7f027ada7bf9.png)
The blue line at the top is cSpell, or specifically the process `/usr/share/vscode/.../extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js`

#### Other running extensions
 - Calculate
 - Overtype
 - Bookmarks
 - Bracket Pair Colorizer 2
 - Disable Ligatures
 - Gitlense
 - Prettier
 - Highlight
 - Todo+
 - LaTeX Workshop
 - Git Indicators
 - Monokai Pro
 - VS Live Share
 - Dictionary Completion

**Comment by Jason3S** [comment]
This can happen after updating VS Code. For some reason there is an abandoned copy of the extension still running.

Please quit VS Code and make sure there are no process still running.  It might show up as `Code Helper`, just kill it and restart VS Code.

It is frustrating when this happens. I think it is related to the client server rpc code, but I haven't had the chance to hunt it down.

**Comment by AlekSi** [comment]
I have the same issue. I quit VS Code, kill that process, start VS Code again, and start working. After some time that helper process is back and consumes 100% of a CPU core.

**Comment by AlekSi** [comment]
And if I kill while VS Code is still running, it is restarted with the same 100% load.
Is there anything I can do to diagnose this issue without knowing anything about JS or extensions development?

**Comment by Jason3S** [comment]
You have to kill the vs code helper process. This only seems to happen durning a VS Code Update. It is very annoying and hard to reproduce.

I am guessing it has something to do with the communication between VS Code and the spell checker processes.

**Comment by Jason3S** [comment]
The best way I found was:
1. Stop VS Code.
1. Check to see if there is a Code Helper process still running.
1. Kill it.
1. Start VS Code again.

**Comment by AlekSi** [comment]
No, it is not related to update. See my first comment.

**Comment by Jason3S** [comment]
@AlekSi Wow, that in not nice. I'm not sure of the issue. Please let me know if it still happens after the latest update.

**Comment by AlekSi** [comment]
I _think_ it no longer happens.

**Comment by Jason3S** [comment]
Thank you. I did try to reproduce it, but I was not able to.
