### ISSUE TITLE
Not updating misspelled word when selecting correction

### ISSUE THREAD

**Issue by ChuckJonas** [Jason-Rev/vscode-spell-checker#308]
Recently this plugin stopped working (which has been really detrimental as I'm a horrible speller!).

It correctly identifies the misspelled words, but when I try to preform the "lightbulb" action to select the correct spelling, it doesn't seem to update the file.

![wbsyk6og0z](https://user-images.githubusercontent.com/5217568/53857882-339b3f00-3f95-11e9-9a76-069561d5b245.gif)

Code: Version 1.31.1 (1.31.1)
OSX: 10.12.6

**Comment by Jason3S** [comment]
That would be very annoying. I have no idea why it stopped working.
What file type is it? Do you have a sample file? It might be related to how the word selection is done.

**Comment by ChuckJonas** [comment]
It started working again...  and I can't seem to repro.  IDK maybe it was a conflict with another extension or something.  I was also having linter issues around the same time /shrug
