### ISSUE TITLE
\nwas will be recognized as 'nwas'

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#31]
![image](https://cloud.githubusercontent.com/assets/11234139/20670227/47d5ed84-b578-11e6-9ba2-05807590ea57.png)

As you may see there, explicit newlines won't be caught.

**Comment by Jason3S** [comment]
Thank you @jens1o .   Nice example image.  This is a duplicate of #7.

**Comment by Jason3S** [comment]
This should be fixed with 0.14.0

**Comment by jens1o** [comment]
God bless you! That's a big help!
