### ISSUE TITLE
Messy in editor context menu

### ISSUE THREAD

**Issue by KamilKot95** [Jason-Rev/vscode-spell-checker#312]
Hi, nice extension, thanks.
But I have one problem, when you use editor context menu you can see 3 rows from spell-checker:
- Show Spell Checker Configuration Info
- Add Word to Folder Dictionary
- Add Word to Global Dictionary

Add word option is displayed when you have unrecognized word in problem fix context menu.

'Show Spell Checker Configuration Info' can be executed from run command (ctrl + shift + P)

This options should be removed in context menu.
If every vscode extension added their options to context menu would be a context menu to display in 2 displays.

**Comment by Jason3S** [comment]
I agree, I'll take it out of the context menu.
