### ISSUE TITLE
Change cSpell.enabledLanguageIds `yml` to `yaml`

### ISSUE THREAD

**Issue by stanvarlamov** [Jason-Rev/vscode-spell-checker#322]
Per [VSC Language Identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers), the official one for YAML is `yaml`. However, [client/package.json](https://github.com/Jason-Rev/vscode-spell-checker/blob/7219d30bd56390b38fe803093fd983f856738e19/client/package.json#L182) uses `yml`. So, getting spell check to work for YAML in VSC 1.33.0 requires a workaround. Suggestion: change `yml` to `yaml`

**Comment by Jason3S** [comment]
Thank you. I'll release a version that has it on by default.
