### ISSUE TITLE
Error in dictionary

### ISSUE THREAD

**Issue by PierreMarchand20** [Jason-Rev/vscode-spell-checker#324]
I noticed that `developped` was not picked up as an error whereas it is misspelled (there should be only one "p"). How can we fix this ?

**Comment by Jason3S** [comment]
I wasn't able to find `developped` in any of the dictionaries. Are you using C/C++ or have `allowCompoundWords` set to true? When it is turned on, it will assume it is two words put together `develop-ped`.

The dictionaries can be found here: [cspell-dicts: Various cspell dictionaries](https://github.com/Jason3S/cspell-dicts)

**Comment by PierreMarchand20** [comment]
You were right, it is because I have `allowCompoundWords` set to true. Thank you for the link, it is good to know ;-)

**Comment by Jason3S** [comment]
Thank you.
