### ISSUE TITLE
This Plugin Is Not Working for Remote files.

### ISSUE THREAD

**Issue by DonaldLouch** [Jason-Rev/vscode-spell-checker#326]
So I've installed the plugin and set the language in VS Code settings with:
`"cSpell.language": "en",`
Followed by:
`"cSpell.enabledLanguageIds": [
        "csharp",
        "go",
        "javascript",
        "javascriptreact",
        "markdown",
        "php",
        "plaintext",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ],`
And:
`"cSpell.enabled": true,`
 `"cSpell.showStatus": true,`

However, the spelling errors are still there with no tip or underline plus the indicator has a (!) beside the cSpell.

Am I doing something wrong?!

**Comment by Jason3S** [comment]
I have an update coming out soon. Hopefully it will address your issue.

**Comment by DonaldLouch** [comment]
Okay thank you!

**Comment by Jason3S** [comment]
I have updated the extension. Please try again. If it still doesn't work, please make a screen shot.

**Comment by DonaldLouch** [comment]
Okay I think it's just not working with my workspace with the [Remote File System for VS Code](https://github.com/liximomo/vscode-remote-fs) extension? It seems to be fine when I don't use that extension! For the screenshots what should I send?

**Comment by Jason3S** [comment]
Ahh, that is it!
It should be possible, but I have never tested it.

You need to add `sftp` or `ftp` to `cSpell.allowedSchemas`:

![image](https://user-images.githubusercontent.com/3740137/56454738-b7e32f00-6355-11e9-999b-364f6ee597d5.png)

![image](https://user-images.githubusercontent.com/3740137/56454759-055f9c00-6356-11e9-8460-204756546186.png)

**Comment by DonaldLouch** [comment]
Perfect :) it's now workingish! I have a new [Error](https://github.com/Jason-Rev/vscode-spell-checker/issues/332) though.

**Comment by DevLexicon** [comment]
Hello,

A few months ago, I started to run into the same issue and cPell no longer works again with my FTP workspace. The allowedSchemes still have ftp and sftp in it's setting.

Thanks!
