### ISSUE TITLE
"No Code Action Available" when using SFTP

### ISSUE THREAD

**Issue by DonaldLouch** [Jason-Rev/vscode-spell-checker#332]
I have a new error. Now that I got the plugin to work on [sFTP/FTP](https://github.com/Jason-Rev/vscode-spell-checker/issues/326) I now can't correct any spelling error. Whenever I do the `command` + `.` method or hover over the misspelt word and click the `Quick Fix` or anything like that I'm presented with "**No Code Action Available**". 

Not sure if I have an incorrect setting or something? Or just doing something wrong?

Screenshot:
https://imgur.com/lkYW5Dw
https://imgur.com/f4Vfklo

**Comment by Jason3S** [comment]
I will take a look when I get a chance.

**Comment by Jason3S** [comment]
@DonaldLouch, Can you try it again? Please make sure you have 1.7.5 or newer.

**Comment by DonaldLouch** [comment]
Still the same message. Updated to version 1.7.5 and still happening.

**Comment by DonaldLouch** [comment]
Now fixed in version 1.7.8 🙌🏻
