### ISSUE TITLE
Adding words to both cspell.json and workspace json?

### ISSUE THREAD

**Issue by werunom** [Jason-Rev/vscode-spell-checker#335]
This issue might be related to [this issue](https://github.com/Jason-Rev/vscode-spell-checker/issues/330). After the recent set of updates (I am using 1.7.4), when I add a word to `workspace dictionary`, the word is getting added to both `cSpell.json` present in the root workspace folder and also to `<workspace>.code-workspace` file. 

Is this expected? Felt like reporting because I remember `add to workspace dictionary` command only updating `cSpell.json`. Moreover, the words `<workspace>.code-workspace` seems not required since removing these words doesnt effect anything...

**Comment by Jason3S** [comment]
It works this way by design. I do need to reevaluate the way the configuration is found. See #315

**Comment by werunom** [comment]
Fine. As mentioned, this is not stopping us from using the extension. Do take your time. I will close this issue.

Thanks for working on this extension :)
