### ISSUE TITLE
en-GB words marked wrongly

### ISSUE THREAD

**Issue by werunom** [Jason-Rev/vscode-spell-checker#338]
After today's release of `1.7.7`, the en-GB words (e.g. `recognise`) are marked as wrong spelt. 

In my `settings.json`, there is already `"cSpell.language": "en-GB"` and things were working fine until this update. Do let me know if I have missed/overlooked something. 

Thank you for this extension :) Will wait for your response...

**Comment by Jason3S** [comment]
Please check to see if you have a cspell.json file.
```
    // language - current active spelling language
    "language": "en",
```

**Comment by werunom** [comment]
Thanks! That solved the issue. (Surprised because before this update `cspell.json` did not have this.)

**Comment by Jason3S** [comment]
The order in which the settings files was changed to better support CI/CD.
