### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HarrylXue** [Jason-Rev/vscode-spell-checker#340]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.7.9`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Henry\streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Jason-Rev** [comment]
Please attach the file. Or I cannot do anything about it.

**Comment by Jason3S** [comment]
I am hoping this is fixed with 1.7.10. I have bundled the extension as described by 

[Explain: extension causes high cpu load · code-loading](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading)
