### ISSUE TITLE
Add fonts

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#35]
Maybe create a new dictionary called fonts? Various fonts are declared as wrong, such as Helvetica Neue etc.

Here my list of fonts(and they're extensions) I use often:
- woff [extension]
- Helvetica Neue
- monospace
- Roboto
- Open Sans
- Arial
- Lucida Grande

Is it possible to export the font list of http://fonts.google.com and use them? That would be great.

**Comment by Jason3S** [comment]
Not a bad idea.  I'll release it with a list of fonts in a few days.

**Comment by jens1o** [comment]
Thanks 😃

**Comment by Jason3S** [comment]
Your welcome.
