### ISSUE TITLE
Add powershell support

### ISSUE THREAD

**Issue by elliot-labs** [Jason-Rev/vscode-spell-checker#36]
Add the ability to spell check powershell files.

Thanks!

**Comment by elliot-labs** [comment]
This may help with the spell checking.

https://gist.github.com/PrateekKumarSingh/1cb264e6e2eb8b2832e9

**Comment by Jason3S** [comment]
Did you try just adding `powershell` to the list of languages to check?

In VS Code user preferences:

```javascript
    // Specify file types to spell check.
    "cSpell.enabledLanguageIds": [
        "csharp",
        "go",
        "javascript",
        "javascriptreact",
        "markdown",
        "php",
        "plaintext",
        "powershell",  // <-- like this.
        "python",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ]
```

If you have a list of keywords, I can add them.  (I don't use powershell, so I am not the best one to add any keywords)

I did open a couple of .ps1 files and didn't see any major issues.

**Comment by elliot-labs** [comment]
Well, after re adding it and restarting my editor it worked. I guess I had to restart the editor.

Thanks!
