### ISSUE TITLE
cSpell.flagWords Unknown configuration setting

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#39]
In VS Code version 1.8.0, cSpell.flagWords is shown as "Unknown configuration setting" in the user settings. In version 1.7.x, I don't think it produced an error. "cSpell.flagWords" doesn't show in the default settings, but all the other settings do. Extension was installed before upgrading to 1.8.0. I've tried uninstalling and re-installing the extension. For now I have commented out, as the error prevents editing other settings.

**Comment by Jason3S** [comment]
Thank you.  I'll follow up and find out what is going on.

**Comment by Jason3S** [comment]
I published a fix.  Please update to 0.13.0.  If it doesn't work for you, please re-open this issue.

**Comment by BillDenton** [comment]
Thanks. Verified fixed.
