### ISSUE TITLE
Right click options

### ISSUE THREAD

**Issue by BramGruneir** [Jason-Rev/vscode-spell-checker#4]
It would be wonderful if there were some options when you right click on a misspelled word.
- add word to user dictionary
- suggested spellings for the word

**Comment by Jason-Rev** [comment]
Hello Bram,

I agree.  I am looking into both options:
1. Adding words to the dictionary.
2. Making spelling suggestions.

At the moment, vscode doesn't support extensions adding items to the right-click menu.  So, I am looking into other ways to make it easy to do those things.

**Comment by Jason-Rev** [comment]
If you update the extension, you can now get suggestions.  When your cursor is on the word, you will see a light-bulb.  Hit ctrl+. (windows) / cmd+. (mac) to get a list of spelling options.

I plan on using the same technique to add words to a user dictionary.

**Comment by Jason-Rev** [comment]
With the 0.10.0 release, it is now possible to use ctrl+. / cmd+. when the light-bulb is showing to add words to the workspace dictionary.

**Comment by BramGruneir** [comment]
@Jason-Rev Just wanted to say thanks for the update!  
It's been working really well!
