### ISSUE TITLE
Mac OS custom dictionary not working

### ISSUE THREAD

**Issue by fieryorc** [Jason-Rev/vscode-spell-checker#40]
Even after I add the words to the dictionary (I tried both project dictionary and global dictionary), the   squigglies don't disappear. This works correctly in Linux, but in my Mac OS (10.12.2), it doesn't work.

**Comment by Jason3S** [comment]
I'll see if I can reproduce it.

Did you add changes directly to cSpell.json or through the commands?

**Comment by fieryorc** [comment]
I never touched the cSpell.json manually. I usually press Ctrl + . and add to project dictionary. It worked until I used the global dictionary. Once I added the project dictionary, it stopped working.

**Comment by Jason3S** [comment]
This should be fixed with 0.14.0
