### ISSUE TITLE
Correction light bulb usually doesn't appear

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#43]
I'm not sure if this a VS Code issue or a spelling checker issue. Errors are underlined (~), but usually the light bulb symbol doesn't appear next the line number in the margin. I notice that is different from your animation where the light bulb appears in the text. Your animation looks better than in the margin. I don't know if there is a setting for this in VS Code. I think I have the same behaviour with code warnings.

**Comment by Jason3S** [comment]
Hello Bill,

It is great that you noticed.  VS Code changed the location of the lightbulb with version 1.6.  It used to be right next to the word.  Now it is on the left margin.   I don't have control of the location, that is a VS Code thing.  I tend to use the short cut keys to get access to the suggestions (CMD+. for mac, and I think CTRL+. for windows).

**Comment by BillDenton** [comment]
I only started using VS Code recently (1.7 I think), so didn't know about the old location. It appears that short cut key (confirmed Ctrl+. in Windows) doesn't work until the light bulb appears. That looks like a VS Code bug.
I also noticed that the local English is American English. Is it possible to get a British dictionary? I have starting adding words (e.g. color) to the flagWords.

**Comment by BillDenton** [comment]
Probably a VS Code issue, see https://github.com/Microsoft/vscode/issues/17540, which is in the January 2017 milestone, so hopefully will be fixed soon.

**Comment by BillDenton** [comment]
With the latest VS Code 1.8.1 and Code Spellchecker 0.14.0 is all works OK. So I'm closing this issue.
