### ISSUE TITLE
Cannot add words to ignore list after recent vscode upate

### ISSUE THREAD

**Issue by laggingreflex** [Jason-Rev/vscode-spell-checker#44]
VSCode version 1.8.1

Cannot add words to ignore list after recent vscode update

Steps to reproduce: 

1. type a word not found in dictionary, eg: "pino"
2. it shows squiggly line underneath it and a light-bulb in the gutter on the left
3. click the light-bulb, it shows various corrections, and an option to "Add: 'pino' to dictionary", choose that option
4. still shows #.2

"Add: 'pino' to project dictionary" doesn't work either, even though the word does gets added to the project's `.vscode/cSpell.json` `"words": ["pino"]` list, it still shows #.2

**Comment by Jason3S** [comment]
Thank you for opening the issue.  VS Code changed the way it works with setting files.  I am working on a fix.

**Comment by laggingreflex** [comment]
Awesome! Adding to project dictionary works. But global dictionary still doesn't... 

![vsspell](https://cloud.githubusercontent.com/assets/2523987/21770261/848f0160-d6a8-11e6-9333-3a18c2208bca.gif)

**Comment by Jason3S** [comment]
Can you update to 0.14.2?  I pushed a fix out for the global dictionary a few minutes ago.

**Comment by laggingreflex** [comment]
ok, so the problem is that "Add to dictionary" in the context menu doesn't actually add the word to `settings.json`'s `cSpell.userWords` list. If I manually add the word in that list myself it does work.

**Comment by BillDenton** [comment]
Works for me in 0.14.2. I think it go fixed for #49

**Comment by laggingreflex** [comment]
@BillDenton  the problem I'm having is that the words are not actually getting added to the `settings.json`'s `cSpell.userWords` list. Could this be an entirely different issue? I'm on Windows

**Comment by Jason3S** [comment]
@laggingreflex where is your settings.json file?

Can you check the contents of both your user level setting.json file and the project level settings.json file?

**Comment by laggingreflex** [comment]
ahh ok, so I found the problem. I had an extra comma in my `settings.json` file. VS code can read the settings file just fine, but it seems it can't actually write or modify it until I removed that extra comma. Whcih is weird because it still allows //comments so I thought the commas wouldn't be a problem and I usually leave extra commas in object literals, but that was the problem.

**Comment by Jason3S** [comment]
Glad you found it.
