### ISSUE TITLE
Spelling medical terms

### ISSUE THREAD

**Issue by DrGo** [Jason-Rev/vscode-spell-checker#45]
Hi Jason,
Is there a way to add an entire custom dictionary to your extension? 
It would be great as I use VSCode for writing academic papers full of medical terms.
here is one possible dictionary 
[https://github.com/Glutanimate/wordlist-medicalterms-en](https://github.com/Glutanimate/wordlist-medicalterms-en)

Thanks for the nice extension,

/salah

**Comment by Jason3S** [comment]
Hello Salah,

I am currently working on a way for you to add your own dictionary.  In the mean time, I'll take a look at the medical terms.

Cheers,
Jason

**Comment by DrGo** [comment]
Great, thanks!

**Comment by Jason3S** [comment]
This feature should be available soon.  Being able to add your own custom dictionary is almost ready.

**Comment by DrGo** [comment]
Thanks Jason,

Much appreciated

**Comment by Jason3S** [comment]
Please checkout [how-to-add-your-own-dictionaries](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md#how-to-add-your-own-dictionaries)

**Comment by DrGo** [comment]
Great, thanks Jason

So good to be able to confidently use favorite terms like Acanthopterygious and Anatidaephobia http://dailyapple.blogspot.in/2011/01/apple-504-fear-of-being-watched-by-duck.html!

**Comment by Jason3S** [comment]
@DrGo in case you are still using this spell checker, I have made installing the medical terms much easier. Check out: [VS Code Medical Terms extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-medical-terms)

**Comment by DrGo** [comment]
Excellent. I will give it a try. Thanks Jason
