### ISSUE TITLE
Extension won't starting

### ISSUE THREAD

**Issue by Viking1983** [Jason-Rev/vscode-spell-checker#47]
Hi,
after VSC starting, The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted. 
VSCode ver: 1.8.1,
Ext ver: 0.14.0
OS: Ubuntu 16.0.4
Best regards,
Paul

**Comment by Jason3S** [comment]
Was there an error message?  This isn't enough for me to go on.

**Comment by micnic** [comment]
Hi, I have the same issue, also in Ubuntu 16.04, VSCode 1.8.1 and extension version 0.14, just after installing the new version I have this error message: "The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted."

![captura de ecran din 2017-01-09 10-44-07](https://cloud.githubusercontent.com/assets/1449826/21760973/0bfab984-d661-11e6-9495-3b5a7e5ec9e3.png)

Screenshot from VSCode developer tools console:
![captura de ecran din 2017-01-09 10-46-17](https://cloud.githubusercontent.com/assets/1449826/21761005/4506326c-d661-11e6-98fa-d7e74d4f7eed.png)

**Comment by Jason3S** [comment]
Thank you.  I'll install ubuntu and see if I can reproduce it.

**Comment by Viking1983** [comment]
Output window is clear. Isn/t an error message is show.

**Comment by Jason3S** [comment]
Thanks guys.  Can you install 0.14.1 and see if it fixes the issue.

**Comment by micnic** [comment]
@Jason3S it works fine for me, thank you very much for such a fast update

**Comment by Jason3S** [comment]
I am running OS X and its file system is case insensitive.  But Ubuntu is case sensitive.  One of the includes had an upper case letter in it.

**Comment by micnic** [comment]
thanks for the info, I checked before the update in Windows and it was working fine, Windows also use a case insensitive file system

**Comment by Viking1983** [comment]
Work's fine. Thanks for quick response and fix problem.
Paul

**Comment by ldsands** [comment]
I seem to be having this issue I has just started in the past couple of days (on a new install of vscode). Any ideas?

![image](https://user-images.githubusercontent.com/7889104/44427223-90359000-a556-11e8-92dc-0239817186b0.png)

**Comment by Jason3S** [comment]
@ldsands did you get it working?

**Comment by ldsands** [comment]
I was able to get it working by wiping my vscode installation I wasn't able to reproduce so no harm done I guess. Thanks for a great extension by the way.
