### ISSUE TITLE
Add support for C and C++

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#48]
Can you add support for C and C++ by creating a dictionary for each of these languages, similar to the language specific dictionary used for example for python. At the moment, for example "#endif" shows as an error. It may be also necessary to add a ignore regrexp to catch "#endif" as elsewhere in the code "endif" should be shown as an error.

**Comment by Jason3S** [comment]
I have added basic support for C and CPP keywords.

**Comment by BillDenton** [comment]
Just updated to 0.14.2. Is it in this release? Thanks.

**Comment by Jason3S** [comment]
I have just added an extensive list of words for C and C++.  It is in 0.14.3.  Can you update your extension and check it out?

**Comment by BillDenton** [comment]
Thanks. It works fine.
