### ISSUE TITLE
Add to dictionary doesn't work and existing entries in user settings are ignored

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#49]
Before update to 0.14.0, I had added all words to the user dictionary using the Add: "word" to dictionary. These words are showing in the user settings.json. I work this way so that the same words are used across all projects/folders. After updating to 0.14.0, all the words in user settings.json are shown as errors and adding to user dictionary doesn't do anything.

**Comment by Jason3S** [comment]
Oops, I forgot to merge in the words from the user setting.

**Comment by Jason3S** [comment]
This fix should be in 0.14.2.  Please try it out.

**Comment by BillDenton** [comment]
Just tested 0.14.2 and it works. Thanks.

**Comment by Jason3S** [comment]
Great!  Thanks for the help.
