### ISSUE TITLE
No Changelog in VS Code extension display

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#50]
Shows "No Changelog available" in VS Code.

**Comment by Jason3S** [comment]
It must be a new setting in the manifest.  I'll look for it.  In the mean time, the release notes are at the bottom of the Extension page.

**Comment by Jason3S** [comment]
I can no longer find the change log link.  Can you add an image showing me where it is?

**Comment by BillDenton** [comment]
Can see full change log just before update to 0.14.3.

**Comment by BillDenton** [comment]
Can see after updating to 0.14.3, so it appears fixed.

**Comment by BillDenton** [comment]
Shows 0.14.5, but change log only shows to 0.14.3. Presume you've been busy fixing issues so haven't yet updated the change log.

**Comment by BillDenton** [comment]
You could also remove the change log from the bottom of the details pane.

**Comment by Jason3S** [comment]
I just figured out what you were referring to.  :-)  The extensions panel in VSCode.

The changelog comes from a file called changlog.md.

**Comment by Jason3S** [comment]
Thank you for pointing this out to me.  I hadn't realized it was blank.

**Comment by BillDenton** [comment]
Confirmed ChangeLog is appearing correctly in 0.14.6 and has been removed from Details pane.
