### ISSUE TITLE
SomeWords\network will fail

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#51]
Consequence of fixing issue #31 
![image](https://cloud.githubusercontent.com/assets/11234139/21769789/c3c289ec-d680-11e6-9ee7-a32e41a99113.png)

Even in the namespace definition in php, this modifier is used. I think the regex should be improved, since this is  a false positive.

**Comment by Jason3S** [comment]
Thank you for the great example.

**Comment by Jason3S** [comment]
This was the result of trying to fix #7 and #31.  I have undone #7 and will look for another solution.

This should now be fixed.  Please re-open if you see any issues with 0.15.0 or newer.
