### ISSUE TITLE
Add support for custom dictionaries

### ISSUE THREAD

**Issue by Jason3S** [Jason-Rev/vscode-spell-checker#52]
Perfect example is #45.  This could be used for languages not yet supported or for domain specific terms, like medical in #45.

This is almost done.  A couple of things are necessary.
1. Add support for dictionary definitions in project.json.
2. Add support for paths relative to the cSpell.json file.

**Comment by BillDenton** [comment]
Is there is any documentation explaining how to use this?

**Comment by Jason3S** [comment]
I'm working on updating the docs on how to do this.

**Comment by Jason3S** [comment]
Can you checkout: [how-to-add-your-own-dictionaries](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md#how-to-add-your-own-dictionaries)
