### ISSUE TITLE
Context helper does not work

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#53]
I was worried when in a other issue an user showed that they are suggestions available. But it doesn't work on my machine. What type of information do you need to help me?

![image](https://cloud.githubusercontent.com/assets/11234139/21770712/bfe4a900-d684-11e6-881b-1ebd37c9175e.png)
As shown in the picture, I don't get any suggestion for "help". In the Developer Tools, they are not any errors in the console which could be useful for you.

**Comment by laggingreflex** [comment]
It's a special menu that opens when you either press <kbd>Ctrl</kbd><kbd>.</kbd> (period) or click the light-bulb icon that appears in the far left gutter.

**Comment by jens1o** [comment]
Ah thanks. I didn't had known that.
