### ISSUE TITLE
Remove closed files in 'Problems' panel 

### ISSUE THREAD

**Issue by stephanedr** [Jason-Rev/vscode-spell-checker#54]
Closing a file that contains errors doesn't remove the associated warnings in the 'Problems' panel, like TS and TSLint do.
Maybe through an option if some people want to keep the current behavior.

**Comment by BillDenton** [comment]
This is an excellent idea. It gets difficult to see the current files in the "Problems" panel. I also have a similar problem with pylint in https://marketplace.visualstudio.com/items?itemName=donjayamanne.python

**Comment by Jason3S** [comment]
Thank you for pointing this out.  There will be a fix in the next release.

**Comment by Jason3S** [comment]
the was fixed in 0.14.4.  Please update the extension and try it out.

**Comment by BillDenton** [comment]
Verified fixed in 0.14.5. Also when switching to a file its problem show at the top of the problem window. This is presumably part of VS Code, but I hadn't noticed it before. I'm not sure if it always behaves like that.

**Comment by stephanedr** [comment]
Working on my side too. Thanks.
