### ISSUE TITLE
cSpell.ignorePaths default paths can not be overwritten

### ISSUE THREAD

**Issue by micnic** [Jason-Rev/vscode-spell-checker#55]
I am developing my node modules inside a `node_modules` directory and wanted to be able to spellcheck the code. I removed the `**/node_modules/**` option from the `cSpell.ignorePaths` array, but the files from the this directory are still not spellchecked. Even if I modify the user or the workspace settings it does not help.

Tested environment:
OS: Ubuntu 16.04
VSCode: 1.8.1
Spell-checker: 0.14.3

**Comment by Jason3S** [comment]
Thank you.  I'll check it out.

**Comment by Jason3S** [comment]
cSpell also excludes the search exclude list. 

```javascript
// Configure glob patterns for excluding files and folders in searches. Inherits all glob patterns from the files.exclude setting.
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
```

Add this to your workspace settings:

```javascript
// Configure glob patterns for excluding files and folders in searches. Inherits all glob patterns from the files.exclude setting.
  "search.exclude": {
    "**/bower_components": true
  },
```

**Comment by micnic** [comment]
I am sorry for being annoying, but it is still not working :)

I added the following settings to the to the workspace:

```json
{
	"cSpell.ignorePaths": [
		"**/vscode-extension/**",
		"**/.git/**",
		".vscode",
		"typings"
	],
	"search.exclude":{
		"**/bower_components": true
	}
}
```

The project has this location:
`/home/micnic/repos/github/node_modules/*MODULE_NAME*`

I played around with different settings and restarting VSCode, but nothing helps. I always get this message at the bottom:
![cspell](https://cloud.githubusercontent.com/assets/1449826/21955652/8a23c828-da80-11e6-842b-02409a18acb3.png)

**Comment by Jason3S** [comment]
I'll take another look.

**Comment by Jason3S** [comment]
This seems to be an issue with VS Code.  It is not honoring the workspace settings.
I just stepped through it with the debugger.  The `**/node_modules` is getting added by VS Code even after I took it out of the `search.exclude` list.

There is a minor bug in how we check the glob, that might fix this issue for you.

In the mean time, there is a work around by using `npm link`.  That allows you to have your node_modules in a different location.

**Comment by micnic** [comment]
Thanks for the information, should this bug be reported to the VSCode repo?

**Comment by Jason3S** [comment]
I think I have fixed the spell checker so it will work in your case.  Please let me know.

**Comment by Jason3S** [comment]
The fix should be in 0.14.6

**Comment by micnic** [comment]
Works fine with 0.14.6, thank you very much

**Comment by SlurpTheo** [comment]
0.14.6 & VS Code: 1.31.1, I can't get files with a `node_modules` somewhere in their path to spell-check.
