### ISSUE TITLE
Highlighting Not Working

### ISSUE THREAD

**Issue by simonyarde** [Jason-Rev/vscode-spell-checker#56]
Followed the install instructions but misspelled words are not highlighted.

What am I missing?

Running latest version of Visual Studio Code.

![visual studio code spell checker highlighting not visible](https://cloud.githubusercontent.com/assets/765361/21927985/3bfb26a6-d980-11e6-9b21-244832c8d4b7.PNG)

**Comment by Jason3S** [comment]
Wow.  That is strange.  Let me check it out.

**Comment by Jason3S** [comment]
It is an issue with opening individual files.  If you open the directory, it will work.
VS Code has two different modes: Individual File or Workspace depending upon how it was started.

**Comment by Jason3S** [comment]
If you update the extension, it should be fixed.

**Comment by simonyarde** [comment]
Thanks Jason, this is now working for me.
