### ISSUE TITLE
Provide npm package with CLI

### ISSUE THREAD

**Issue by clavecoder** [Jason-Rev/vscode-spell-checker#58]
If you look at the example of [markdownlint], I'm not only able to globally and locally suppress checks, I can use an [npm package for the code] and a [cli npm pacakge] to add the linting to my build process.

This should be added for cSpell. For better form the `.vscode/cSpell.json` file should probably be put in the root as a `.cspellrc.json` file.

If interested, I would also recommend that a `cspell` npm package (and yes it *is* available) should include the CLI.

[markdownlint]: https://code.visualstudio.com/Docs/languages/markdown
[npm package for the code]: https://www.npmjs.com/package/markdownlint
[cli npm pacakge]: https://www.npmjs.com/package/markdownlint-cli

**Comment by Jason3S** [comment]
Thank you for your suggestion.  This is similar to #34.

To help me understand, why `.cspellrc.json` instead of just `cSpell.json`?

**Comment by Jason3S** [comment]
Please try:
```
npm install -g cspell
```

I am still working on the documentation, but the following should work:

```
cspell -v "**/*.js"
```

**Comment by Jason3S** [comment]
I'm going to close this for now. Please open any new issues here: cspell/issues

**Comment by Javrd** [comment]
Please document a little this. At least refer that the CLI exists in the [VS Code marktplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by vajahath** [comment]
@Jason3S 
as @Javrd said, it's better to document this in the extension. I was going to open an issue of cli support. Then I found this thread.
