### ISSUE TITLE
Add *insert programming language here* support

### ISSUE THREAD

**Issue by nicojs** [Jason-Rev/vscode-spell-checker#60]
It would be nice if we could add support our own programming language. 

For example, I'm using [pugjs](https://github.com/pugjs/pug) to generate my static web site. `*.pug` files can contain markdown, (pseudo) html, etc. How could i add support for that in cSpell?

**Comment by Jason3S** [comment]
You have to add it to your user settings.

If you hover your mouse over the spell checker part of the status bar, it shows the file type:

![jadenotenabled](https://cloud.githubusercontent.com/assets/3740137/21965397/64c75916-db5f-11e6-83ee-ded4322ff813.png)

I am working on a way to make it easier, but for now you need to edit your user settings is VS Code.  

<img width="315" alt="screen shot 2017-01-15 at 8 20 04 pm" src="https://cloud.githubusercontent.com/assets/3740137/21965440/13d639fe-db60-11e6-9965-1aac5a460d48.png">

**Comment by Jason3S** [comment]
You might need to restart VS Code for the setting to take effect.

**Comment by Jason3S** [comment]
Pug is now turned on by default.
I have associated the following dictionaries with pug:
`'html', 'fonts', 'typescript', 'css', 'npm'`
This should take care of most syntax needs.

**Comment by Jason3S** [comment]
I'll close this issue for now.

**Comment by nicojs** [comment]
Thank you! The work around also worked btw. Are you going to rename jade to pug?
