### ISSUE TITLE
readonly in c#?

### ISSUE THREAD

**Issue by rakkarage** [Jason-Rev/vscode-spell-checker#62]
![2017-01-17 2](https://cloud.githubusercontent.com/assets/962340/22034215/81d65358-dcb9-11e6-8c7e-0211c674c5dd.png)

thanks! :)

edit: oh I guess we have to add keywords ourselves somehow

**Comment by Jason3S** [comment]
I have not yet added keywords for cSharp.  I still need a list of keywords and common library methods.

**Comment by Jason3S** [comment]
This should now be fixed with 0.15.0.  Please update the extension.
