### ISSUE TITLE
Add "Toggle Spell Checking for Workspace" command

### ISSUE THREAD

**Issue by blackwind** [Jason-Rev/vscode-spell-checker#64]
I'd like to see a toggle command, `cSpell.toggleForWorkspace`, so I can bind it to a single keyboard shortcut.

**Comment by Jason3S** [comment]
There are a few commands I plan on adding as well:
- *enable(ForWorkspace)* 
   -- turn on spell checker (for the workspace)
- *disable(ForWorkspace)* 
   -- turn off spell checker (for the workspace)
- *toggle(ForWorkspace)* 
   -- toggle on / off the spell checker (for the workspace).
- *enableCurrentLanguage(ForWorkspace)* 
   -- turn on checking the language of the current document.
- *disableCurrentLanguage(ForWorkspace)*
   -- turn off checking the language of the current document.
- *toggleCurrentLanguage(ForWorkspace)* 
   -- toggle on / off the current language

**Comment by Jason3S** [comment]
Update: I still think this is a good idea, I just haven't had the time to do it.  I am open for *pull requests*.

**Comment by Jason3S** [comment]
All the commands have been added except for toggleCurrentLanguage.
