### ISSUE TITLE
Allow to customize cSpell.json file location

### ISSUE THREAD

**Issue by mlewand** [Jason-Rev/vscode-spell-checker#70]
Hi, current `cSpell.json` file location makes it easy to confuse it with actual project files. It would make sense to put it in `.vscode/cSpell.json` directory (not to distract people not using VSCode).

Since this change would be backward incompatible I'd suggest adding a config option, allowing one to override (even on per project-basis) `cSpell.json` location.

Great extension btw, keep it up!

If you're fine with that, and like to get it as a pull request, I'd be happy to contribute.

**Comment by Jason3S** [comment]
Hello,

Thank you for the feed back.  I see your point.  If you move the file to .vscode/cSpell.json, it should work.

The extension searches multiple locations for the file: .vscode, and project root.

I have also gotten the opposite request (moving it out of .vscode) so projects can share the spelling configuration.

I think you make a good point to keep the default location of cSpell.json in .vscode.

**Comment by mlewand** [comment]
Ohh, that's great - just did it and it works fine. Actually it's even mentioned in readme, somehow I missed it:

> Words added to the dictionary are placed in the `cSpell.json` file in the `.vscode` folder found in the _workspace_.
> Note, the settings in cSpell.json will override the equivalent cSpell settings in settings.json.

What was problem for me is the fact that by default it was placed in project dir instead of `.vscode` - but seeing you have requests for both strategies, there's no ultimate solution for this. 🙂

In that regard issue is closed, thanks.

**Comment by MartinSGill** [comment]
It might be worth adding `.cspell` to the searched files. That way it could also follow the *nix convention for configuration files.

I have to admit though that I'm getting a little tired of all the config files I have, from tsconfig, to gitignore, npmignore, yarn.lock and so many more, that on some projects I've got more configuration files than source files.
