### ISSUE TITLE
Repeated characters don't give appropriate spelling suggestion

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#73]
I accidentally typed "oone". The spelling suggestions only included four letter words (none, bone, done, gone, etc). It would be good if could suggest "one". Not sure how to do this, but the spelling corrector in Chrome and Firefox suggest "one".

**Comment by Jason3S** [comment]
Strange.

This is what I get:
![image](https://cloud.githubusercontent.com/assets/3740137/23544084/ae75ccd6-fff5-11e6-8a2e-bd02d2ecc5f0.png)

**Comment by BillDenton** [comment]
Also, strange another Windows Professional 7 PC with just this extension loaded on release 1.10.1 it works with "one", showing in the list. But the order is different:
![untitled](https://cloud.githubusercontent.com/assets/17859340/23549161/be73506a-0002-11e7-9dfc-f5847d69db6e.png)
On the original PC with same version of Windows and VS Code it doesn't work. Note there are other extensions loaded.
![untitled1](https://cloud.githubusercontent.com/assets/17859340/23549645/1b473a52-0005-11e7-8c8d-76afad99f290.png)

**Comment by Jason3S** [comment]
What version of the Spell Checker do you have?  The current version is 0.17.2

![image](https://cloud.githubusercontent.com/assets/3740137/23554274/a9e64c84-0024-11e7-9a73-2ef01895e5a0.png)

**Comment by BillDenton** [comment]
There's something strange going on. On my laptop the extension is on 0.17.2, but on my desktop is stuck on 0.14.8. After uninstalling and reinstalling the extension it is now 0.17.2.  It now works on my desktop as well. The word order is still different to your screenshot, but that doesn't matter. I wonder why the extension got stuck on a older version. I doubt that this anything specific to this extension.
Will close as problem was caused by out of date version.
