### ISSUE TITLE
Can’t handle contractions with true apostrophe

### ISSUE THREAD

**Issue by GlenPerkins** [Jason-Rev/vscode-spell-checker#80]
Words such as couldn’t, didn’t, wouldn’t, etc. are flagged as misspelled if they use a true apostrophe (right single quote). Contractions that use the old ASCII single quote work: couldn't, didn't, wouldn't.

**Comment by Jason3S** [comment]
You are right.

**Comment by Jason3S** [comment]
Task: map `’` to `'` before spell checking.

**Comment by thorn0** [comment]
In JS strings, there is also a problem with escaping: `'transition hasn\'t been started'`. The spell checker complains about `hasn`.

**Comment by Jason3S** [comment]
Thank you. That is also an issue.
