### ISSUE TITLE
Per language settings

### ISSUE THREAD

**Issue by kaitian-xie** [Jason-Rev/vscode-spell-checker#84]
Is it possible to set ignoreRegExp/includeRegExp for different programming languages?

**Comment by Jason3S** [comment]
Yes it does.  When I get a few minutes, I'll post an example on how to do this.

**Comment by Jason3S** [comment]
There was a bug in the per-language settings. This has now been fixed.

Each language can have its own settings.  Any settings available at the global level are available at the language level.

**Comment by Jason3S** [comment]
Please re-open if you have any questions.
