### ISSUE TITLE
Check all files in the workspace

### ISSUE THREAD

**Issue by hermanbergwerf** [Jason-Rev/vscode-spell-checker#85]
I would like to, at some point, check for spelling errors throughout my entire project. Perhaps there is a setting for this already but I didn't see one.

**Comment by Jason3S** [comment]
How about a command line version: [cspell](https://www.npmjs.com/package/cspell)?

After installing it, you can run it in the terminal (even in VS Code):

```sh
cspell  **/*.ts
```
This will check all *typescript* files.

**Comment by hermanbergwerf** [comment]
Pretty cool! I think that would satisfy my needs. Thanks.

**Comment by Jason3S** [comment]
This extension uses the *cspell* library for spell checking.  I'll close this issue for now.  If you have any more questions, please feel free to ask.
