### ISSUE TITLE
Words in the forbidden list are being shown as suggested spelling corrections

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#89]
From https://github.com/Jason-Rev/vscode-spell-checker/issues/74

Words in the forbidden list are being suggested (because the are in one of the active dictionaries).
This is a valid issue. It is a bit strange from a usability perspective. The issue is that forbidden words are not filtered out of the suggestion list before it is presented. If you think this is a big issue, please create a new issue. It is a perfect candidate for a pull request.

Code Spellchecker version 1.1.0
VS Code Version 1.11.2 on Windows 7

**Comment by Jason3S** [comment]
I think your suggestion is correct.  Forbidden words should be filtered out of suggestions.

**Comment by Jason3S** [comment]
This should be fixed.
