### ISSUE TITLE
The spellCheckDelayMs timeout doesn't seem to be reset as you type.

### ISSUE THREAD

**Issue by rzvc** [Jason-Rev/vscode-spell-checker#90]
As the title says, the timeout that triggers the spellcheck, doesn't seem to be reset if you type more characters into the current word, so if the word is long enough and the timeout expires, it will spellcheck before you're done writing the word.

**Comment by Jason3S** [comment]
Thank you for the feedback. You are right. It is programmed as a debounce. I can see how waiting for the last keystroke might provide a better experience.

**Comment by Jason3S** [comment]
This should be fixed with the latest release.

**Comment by stefan-titus-keysight** [comment]
I can confirm that this is working as desired in 1.3.0. 

Good timing, too. I was just trying to fix it myself last week, and my solution would not have been nearly so elegant.

Thanks,
--Stefan
