### ISSUE TITLE
allowCompoundWords does not work in .vscode/cSpell.json

### ISSUE THREAD

**Issue by mikew** [Jason-Rev/vscode-spell-checker#93]
Not sure if this is intended behaviour or not, but setting `"allowCompoundWords": true` in `.vscode/cSpell.json` does not work.

**Comment by Jason3S** [comment]
Can you give some examples? If you give me some words you would expect to work, but do not, then I have a better idea where the issue might be.

What type of file is it? .txt, .cpp, .py, etc.

**Comment by mikew** [comment]
It's not related to any single file type. But let's use the word `splashscreen` as an example.

By default this gets flagged, which is fine.

Changing `cSpell.allowCompoundWords` to `true` in your VS Code **global** settings lets this word be considered valid.

I expected the **local** `.vscode/cSpell.json` to also accept that option. It doesn't.

**Comment by Jason3S** [comment]
Thank you for reporting this.

**Comment by Jason3S** [comment]
This should be fixed with the latest version of the plug-in. Please reopen if it still is an issue.
