### ISSUE TITLE
"search.exclude" setting affects "cSpell.ignorePaths"

### ISSUE THREAD

**Issue by nikolay-borzov** [Jason-Rev/vscode-spell-checker#95]
If you specify:
```json
"search.exclude": {
  "dist": true
}
```
then sub-folder `dist/` is ignored by the spell checker.

It does make sense though, but not obvious

**Comment by Jason3S** [comment]
You make a good point, it is not obvious. But it does ignore the search exclude by default. That was a feature request.

Do you have any suggestions on how to communicate this in a more obvious way?

**Comment by nikolay-borzov** [comment]
I guess we can add a note on the help page - something about relying on VS Code search engine

**Comment by Jason3S** [comment]
I have starting documenting this behavior in the [FAQ](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/FAQ.md)
