### ISSUE TITLE
UI issue with dark themes

### ISSUE THREAD

**Issue by cfjedimaster** [Jason-Rev/vscode-spell-checker#96]
It's a real minor thing, but the DIsable/Enable links are very hard to read when using a dark theme.

![image](https://cloud.githubusercontent.com/assets/393660/26685667/5f7705a8-46b0-11e7-8d97-fc9191e5997e.png)

**Comment by Jason3S** [comment]
Good find. I'll have to look for a fix for this one.

**Comment by Jason3S** [comment]
This seems to be an issue with VSCode.  There doesn't seem to be a way configure links with themes.

**Comment by cfjedimaster** [comment]
I'll file a bug report there.

**Comment by Jason3S** [comment]
Since I cannot get the color of links to be compatible with the theme color, I took a different approach.

![image](https://user-images.githubusercontent.com/3740137/27260134-5f3e7626-5424-11e7-9c7e-4f6929d03051.png)

**Comment by Jason3S** [comment]
This will go out with 1.2.1.

**Comment by cfjedimaster** [comment]
looks good!

**Comment by Jason3S** [comment]
I just released 1.2.1. It should be fixed.
