### ISSUE TITLE
Status bar is hard to read with light themes

### ISSUE THREAD

**Issue by szafranek** [Jason-Rev/vscode-spell-checker#97]
![image](https://user-images.githubusercontent.com/152606/26996693-47dca248-4d74-11e7-9303-89b127458d0b.png)

When using a light theme, such as Solarized Light, the status bar text is very difficult to read, because the extension hardcodes the foreground color to white.

The extension should respect theme settings for the status bar.

**Comment by Jason3S** [comment]
You are right!

**Comment by Jason3S** [comment]
Being able to reference the theme colors was a recent change.

**Comment by Jason3S** [comment]
If you update the plug-in to 1.2.0, this should be fixed.

**Comment by szafranek** [comment]
That was amazingly quick, thank you!

Great extension, BTW. Lack of integration with the native spellchecker on Mac is a major issue, and your extension makes VSC usable again for me.

**Comment by Jason3S** [comment]
Your welcome.

I wrote the extension because I needed a spell checker.

It is open source, so feel free to make improvements.

Cheers,
Jason
