### ISSUE TITLE
Using &mdash; in markdown will result in an error

### ISSUE THREAD

**Issue by michael-yx-wu** [Jason-Rev/vscode-spell-checker#98]
Using `&mdash;` in markdown files will result in a spelling error.

**Comment by Jason3S** [comment]
good catch, I'll have to think about how to catch that one.

**Comment by Jason3S** [comment]
@michael-yx-wu 
Can you try using this cspell addon?
[cspell-dict-html-symbol-entities](https://www.npmjs.com/package/cspell-dict-html-symbol-entities)

It works with version 1.3.0 and new of the spell checker.

I might include it by default in future versions of the spell checker.

**Comment by michael-yx-wu** [comment]
Nice that works for me

**Comment by Jason3S** [comment]
Nice to hear.  I'll close this issue.
