### ISSUE TITLE
Not working before document is saved

### ISSUE THREAD

**Issue by iddan** [Jason-Rev/vscode-spell-checker#99]
When creating new document but not saving it spell checker doesn't work.

**Comment by Jason3S** [comment]
Thank you.

Until the document is saved, we do not know what type of file it is. It is a sort of special temporary file in VS Code. As a rule, we do not spell check temporary scratch files created by VS Code (it creates a lot of them).

**Comment by iddan** [comment]
I often set a language for temporary files, when set I think it can start spell checking

**Comment by bording** [comment]
@Jason3S Would it be possible to reconsider this behavior? I often open VS Code directly and start typing into the default "Untitled-1" plaintext file with no intention of saving it. Not having these files spellchecked is very annoying.

I used to use Sublime Text for this exact thing, and the spell check there works in this case. I'd love to be able to use this same workflow in VS Code!

![untitled-1](https://user-images.githubusercontent.com/753669/27763590-2398c2b8-5e54-11e7-9dff-40899272f0e1.png)

**Comment by Jason3S** [comment]
Thank you for the up-vote. I need to investigate how to distinguish between temporary documents created by VS Code and other plugins from newly created documents.

**Comment by nilact** [comment]
In Windows, it creates unsaved file at below location:

C:\Users\**{WindowsUserName}**\AppData\Roaming\Code\Backups\

Any way to exclude this path?

**Comment by Jason3S** [comment]
I believe this is now working with 1.3.6 version of the spell checker. Please re-open if it is not.

**Comment by iddan** [comment]
it is
